import glyphData from "@/data/radicals/glyphs.json";

import { SUBJECT_TYPES } from "./domainConstants";

/**
 * The glyph for a WaniKani radical the API never gave a character to.
 *
 * Fifteen of the 504 radicals arrive with `characters` empty. WaniKani draws
 * those as artwork on its own gated CDN, so every surface here fell back to
 * printing the slug and a review of 旅 asked the member to recognise the
 * English word "tofu".
 *
 * Nine of the fifteen are ordinary Unicode characters WaniKani simply left
 * blank. The other six are shapes Unicode does not encode at all and take
 * private-use codepoints, which only `public/fonts/umakuma-radicals-*.woff2`
 * can draw - so the font is not decoration, it is the only thing that renders
 * those six. Both kinds are plain text either way, which is the point: they
 * size with `glyphTextSizeClass`, inherit colour, and need no branch at the
 * call site.
 *
 * The map is generated by `pnpm radicals:font` from the same table that builds
 * the font, so a codepoint cannot drift between the two.
 *
 * This is deliberately not stored on `WkSubjectCatalog.characters`: the catalog
 * sync writes that column from the API payload on every update, so a value
 * written here would be erased by the next sync.
 */
type RadicalGlyphEntry = { glyph: string; encoded: boolean };

const RADICAL_GLYPHS: Record<string, RadicalGlyphEntry> = glyphData.glyphs;

/** The glyph for a radical slug, or null if WaniKani gave that one a character. */
export function radicalGlyphForSlug(slug: string | null | undefined): string | null {
  const trimmed = slug?.trim();
  if (!trimmed) return null;
  return RADICAL_GLYPHS[trimmed]?.glyph ?? null;
}

/**
 * What to draw for a subject, given whatever the catalog holds.
 *
 * Radicals are the only subject type that can arrive without characters, so
 * everything else short-circuits to its own characters. Returns null when
 * there is nothing to draw at all, which callers already handle by falling
 * back to the slug.
 */
export function resolveSubjectGlyph(subject: {
  subjectType: string | null | undefined;
  characters: string | null | undefined;
  slug: string | null | undefined;
}): string | null {
  const characters = subject.characters?.trim();
  if (characters) return characters;
  if (subject.subjectType !== SUBJECT_TYPES.radical) return null;
  return radicalGlyphForSlug(subject.slug);
}

/** True when the glyph can only be drawn by the bundled font. */
export function isPrivateUseGlyph(glyph: string | null | undefined): boolean {
  if (!glyph) return false;
  const codepoint = glyph.codePointAt(0);
  return codepoint !== undefined && codepoint >= 0xe000 && codepoint <= 0xf8ff;
}

/** Every slug the font carries, for tests and the proof sheet. */
export const RADICAL_GLYPH_SLUGS = Object.keys(RADICAL_GLYPHS);
