import type { ReleaseCodename } from "./releaseCodenames";

/** Releases 221 to 440. See `releaseCodenameList.ts`. */
export const CODENAMES_PART_2: readonly ReleaseCodename[] = [
  { romaji: "Arabia no Suuji", ja: "アラビアの数字", reading: "あらびあのすうじ", gloss: "the digits everyone types" },
  { romaji: "Ichiran no Waku", ja: "一覧の枠", reading: "いちらんのわく", gloss: "one frame for every list" },
  { romaji: "Ukabu Uchigawa", ja: "浮かぶ内側", reading: "うかぶうちがわ", gloss: "the inside of a character, surfacing" },
  { romaji: "Eranda Ashimoto", ja: "選んだ足元", reading: "えらんだあしもと", gloss: "one footing, chosen for every card" },
  { romaji: "Onaji Choumen", ja: "同じ帳面", reading: "おなじちょうめん", gloss: "one ledger, kept by everyone" },
  { romaji: "Kazoete Kakunin", ja: "数えて確認", reading: "かぞえてかくにん", gloss: "counted, and checked against its source" },
  { romaji: "Kikoeru Kigou", ja: "聞こえる記号", reading: "きこえるきごう", gloss: "a reading you can hear as well as see" },
  { romaji: "Kunda Junban", ja: "組んだ順番", reading: "くんだじゅんばん", gloss: "the order it was queued in" },
  { romaji: "Keizoku no Kekka", ja: "継続の結果", reading: "けいぞくのけっか", gloss: "what keeping at it adds up to" },
  { romaji: "Koko no Kotae", ja: "個々の答え", reading: "ここのこたえ", gloss: "each thing in its own place" },
  { romaji: "Sashikomu Sou", ja: "差し込む層", reading: "さしこむそう", gloss: "slid into the layer it belongs to" },
  { romaji: "Shizumeta Shihyou", ja: "静めた指標", reading: "しずめたしひょう", gloss: "the target, brought down to size" },
  { romaji: "Sunao na Iriguchi", ja: "素直な入口", reading: "すなおないりぐち", gloss: "an entrance that does what it says" },
  { romaji: "Setsuzoku no Kinjo", ja: "接続の近所", reading: "せつぞくのきんじょ", gloss: "the neighbourhood, joined up" },
  { romaji: "Sonaeta Shotai", ja: "備えた書体", reading: "そなえたしょたい", gloss: "the faces a learner meets, provided" },
  { romaji: "Tabaneta Tegakari", ja: "束ねた手掛かり", reading: "たばねたてがかり", gloss: "the clues, bundled as they are found" },
  { romaji: "Chokusetsu Tadoru", ja: "直接辿る", reading: "ちょくせつたどる", gloss: "reached directly, by its address" },
  { romaji: "Tsunagatta Tochi", ja: "繋がった土地", reading: "つながったとち", gloss: "the land, joined up and read" },
  { romaji: "Tezawari no Haba", ja: "手触りの幅", reading: "てざわりのはば", gloss: "wide enough to reach the column" },
  { romaji: "Toriyoseta Shina", ja: "取り寄せた品", reading: "とりよせたしな", gloss: "the items, gathered as what they are" },
  { romaji: "Nazuketa Juusho", ja: "名付けた住所", reading: "なづけたじゅうしょ", gloss: "an address with a name on it" },
  { romaji: "Nita Mono", ja: "似た物", reading: "にたもの", gloss: "a copy that is yours, or theirs to keep" },
  { romaji: "Nushi ga Kimeru", ja: "主が決める", reading: "ぬしがきめる", gloss: "the owner decides" },
  { romaji: "Nekasete Mamoru", ja: "寝かせて守る", reading: "ねかせてまもる", gloss: "put to rest, and kept for those who hold it" },
  { romaji: "Nokeru Kioku", ja: "除ける記憶", reading: "のけるきおく", gloss: "what you already know, set aside" },
  { romaji: "Hazushite Modoru", ja: "外して戻る", reading: "はずしてもどる", gloss: "taken out, and back where you started" },
  { romaji: "Hiroeru Hibiki", ja: "拾える響き", reading: "ひろえるひびき", gloss: "a sound you can pick up, however you type it" },
  { romaji: "Fueru Mokuroku", ja: "増える目録", reading: "ふえるもくろく", gloss: "a catalogue that keeps itself" },
  { romaji: "Herashite Tsukuru", ja: "減らして作る", reading: "へらしてつくる", gloss: "cut down first, then made" },
  { romaji: "Honno Issatsu", ja: "ほんの一冊", reading: "ほんのいっさつ", gloss: "several lists, just the one volume" },
  { romaji: "Manabu Atsumari", ja: "学ぶ集まり", reading: "まなぶあつまり", gloss: "everything to learn from, gathered in one place" },
  { romaji: "Mittsu Hitotsu", ja: "三つ一つ", reading: "みっつひとつ", gloss: "three ways in, one view" },
  { romaji: "Mukau Saki", ja: "向かう先", reading: "むかうさき", gloss: "somewhere to go, with or without a connection" },
  { romaji: "Medatsu Yobikata", ja: "目立つ呼び方", reading: "めだつよびかた", gloss: "called what it is for" },
  { romaji: "Mou Deta", ja: "もう出た", reading: "もうでた", gloss: "already out, not asked twice" },
  { romaji: "Yasashiku Yomeru", ja: "優しく読める", reading: "やさしくよめる", gloss: "every pill says what it is" },
  { romaji: "Yuruyaka na Soroi", ja: "緩やかな揃い", reading: "ゆるやかなそろい", gloss: "every page in the same clothes" },
  { romaji: "Yosooi wo Awaseru", ja: "装いを合わせる", reading: "よそおいをあわせる", gloss: "the same top on every page" },
  { romaji: "Rakuraku Modoreru", ja: "楽々戻れる", reading: "らくらくもどれる", gloss: "the address brings you back" },
  { romaji: "Rikai shiyasui", ja: "理解しやすい", reading: "りかいしやすい", gloss: "a panel you can actually read" },
  { romaji: "Ruupu de Kakomu", ja: "ループで囲む", reading: "るーぷでかこむ", gloss: "the far islands, framed apart" },
  { romaji: "Renraku Michishirube", ja: "連絡道標", reading: "れんらくみちしるべ", gloss: "an address you can hand to somebody" },
  { romaji: "Rokusen Kazoe", ja: "六線数え", reading: "ろくせんかぞえ", gloss: "counted by the strokes it takes" },
  { romaji: "Wasurenai Katahou", ja: "忘れない片方", reading: "わすれないかたほう", gloss: "a word and its kanji, both kept" },
  { romaji: "Anzan Irazu", ja: "暗算いらず", reading: "あんざんいらず", gloss: "the era year, without the arithmetic" },
  { romaji: "Ima no Souba", ja: "今の相場", reading: "いまのそうば", gloss: "today's rate, in the search box" },
  { romaji: "Umaku Tsunagaru", ja: "うまく繋がる", reading: "うまくつながる", gloss: "your own reviews, brought across" },
  { romaji: "En no Nijuunen", ja: "円の二十年", reading: "えんのにじゅうねん", gloss: "twenty years of the yen, on one line" },
  { romaji: "Oshitsukenai Annai", ja: "押し付けない案内", reading: "おしつけないあんない", gloss: "nothing offered that you cannot open" },
  { romaji: "Kazoku no Kakoi", ja: "家族の囲い", reading: "かぞくのかこい", gloss: "the family's own circle" },
  { romaji: "Kimaru Doru", ja: "決まるドル", reading: "きまるどる", gloss: "which dollar you meant, settled" },
  { romaji: "Kuwaeru Ichigyou", ja: "加える一行", reading: "くわえるいちぎょう", gloss: "one line added above the rows" },
  { romaji: "Kettei Mae no Reberu", ja: "決定前のレベル", reading: "けっていまえのれべる", gloss: "the level before it is settled" },
  { romaji: "Konomi no Kakikata", ja: "好みの書き方", reading: "このみのかきかた", gloss: "a price written the way you write it" },
  { romaji: "Sakanoboru Goukaku", ja: "遡る合格", reading: "さかのぼるごうかく", gloss: "every pass, going back" },
  { romaji: "Shikikin no Keta", ja: "敷金の桁", reading: "しききんのけた", gloss: "the deposit read at the right number of zeros" },
  { romaji: "Sugu Wakaru Yurai", ja: "すぐ分かる由来", reading: "すぐわかるゆらい", gloss: "where a list came from, at a glance" },
  { romaji: "Seiretsu Naoshi", ja: "整列直し", reading: "せいれつなおし", gloss: "the facts line up where they belong" },
  { romaji: "Sonaeru Bushu", ja: "備える部首", reading: "そなえるぶしゅ", gloss: "the radicals a character is made ready from" },
  { romaji: "Tatta Hitokoto", ja: "たった一言", reading: "たったひとこと", gloss: "one line saying why it is here" },
  { romaji: "Chuumon no Kensaku", ja: "注文の検索", reading: "ちゅうもんのけんさく", gloss: "the search you type as a command" },
  { romaji: "Tsumete Narabu", ja: "詰めて並ぶ", reading: "つめてならぶ", gloss: "the grid packed into fewer rows" },
  { romaji: "Temoto Techou", ja: "手元手帳", reading: "てもとてちょう", gloss: "the notebook kept at hand" },
  { romaji: "Touitsu no Ookisa", ja: "統一の大きさ", reading: "とういつのおおきさ", gloss: "one size for both search boxes" },
  { romaji: "Nazoru Katachi", ja: "なぞる形", reading: "なぞるかたち", gloss: "a shape traced for every radical" },
  { romaji: "Nihongo Igai", ja: "日本語以外", reading: "にほんごいがい", gloss: "a radical named in English too" },
  { romaji: "Nukete Hirogaru", ja: "抜けて広がる", reading: "ぬけてひろがる", gloss: "the links step out and the box widens" },
  { romaji: "Nebari no Bangou", ja: "粘りの番号", reading: "ねばりのばんごう", gloss: "the numbers you can finally stay with" },
  { romaji: "Nozoku Botan", ja: "覗くボタン", reading: "のぞくぼたん", gloss: "the button that waits until you look" },
  { romaji: "Hanareru Aida", ja: "離れる間", reading: "はなれるあいだ", gloss: "the space that opens between the numbers" },
  { romaji: "Hitofude Hanshi", ja: "一筆半紙", reading: "ひとふではんし", gloss: "a single brushstroke on writing paper" },
  { romaji: "Futatsu Hikaeru", ja: "二つ控える", reading: "ふたつひかえる", gloss: "the two sections that stand aside" },
  { romaji: "Hen na Ten", ja: "変な点", reading: "へんなてん", gloss: "the dot that was reading as a break" },
  { romaji: "Hoshii Meibo", ja: "欲しい名簿", reading: "ほしいめいぼ", gloss: "the list you wanted to see" },
  { romaji: "Mataseru Owari", ja: "待たせる終わり", reading: "またせるおわり", gloss: "the end of being kept waiting" },
  { romaji: "Mitorizu no Machikado", ja: "見取り図の街角", reading: "みとりずのまちかど", gloss: "a street corner with a map on it" },
  { romaji: "Musubu Shiori", ja: "結ぶ栞", reading: "むすぶしおり", gloss: "the list, tied to what it means" },
  { romaji: "Mekuranai Mekata", ja: "めくらない目方", reading: "めくらないめかた", gloss: "weighed without turning a page" },
  { romaji: "Mochikaeru Tsuika", ja: "\u6301\u3061\u5e30\u308b\u8ffd\u52a0", reading: "\u3082\u3061\u304b\u3048\u308b\u3064\u3044\u304b", gloss: "the additions you take home from the original" },
  { romaji: "Yamu Chiratsuki", ja: "止むちらつき", reading: "やむちらつき", gloss: "the flicker that stops" },
  { romaji: "Yuruganai Hyoumen", ja: "揺るがない表面", reading: "ゆるがないひょうめん", gloss: "a surface that does not shift" },
  { romaji: "Yosoou Hitokumi", ja: "装う一組", reading: "よそおうひとくみ", gloss: "one set, dressed alike" },
  { romaji: "Raihou", ja: "来訪", reading: "らいほう", gloss: "a visit, calling on somebody else" },
  { romaji: "Rinsho no Ikkaku", ja: "臨書の一画", reading: "りんしょのいっかく", gloss: "one stroke of the model you are copying" },
  { romaji: "Ruiji no Ruisui", ja: "類似の類推", reading: "るいじのるいすい", gloss: "inferring one link from another because they look alike" },
  { romaji: "Rekkyo", ja: "列挙", reading: "れっきょ", gloss: "listing things out, one page at a time" },
  { romaji: "Rouka no Isshitsu", ja: "廊下の一室", reading: "ろうかのいっしつ", gloss: "one room off the corridor, with a door of its own" },
  { romaji: "Watasu Tanomi", ja: "渡す頼み", reading: "わたすたのみ", gloss: "the request, handed across" },
  { romaji: "Akeru Aikagi", ja: "開ける合鍵", reading: "あけるあいかぎ", gloss: "one spare key, and it opens all three" },
  { romaji: "Ireru Ibasho", ja: "入れる居場所", reading: "いれるいばしょ", gloss: "the place to put it, from where you found it" },
  { romaji: "Uketoru Bun Dake", ja: "受け取る分だけ", reading: "うけとるぶんだけ", gloss: "only the part you take" },
  { romaji: "Eru Atesaki", ja: "得る宛先", reading: "えるあてさき", gloss: "the address it actually reaches" },
  { romaji: "Otagai no Oboe", ja: "お互いの覚え", reading: "おたがいのおぼえ", gloss: "what each other has learned" },
  { romaji: "Kaeseru Kirikae", ja: "返せる切り替え", reading: "かえせるきりかえ", gloss: "a switch that goes back" },
  { romaji: "Kikanai Kariban", ja: "聞かない仮番", reading: "きかないかりばん", gloss: "the stand-in it stops asking about" },
  { romaji: "Kurai Mama", ja: "暗いまま", reading: "くらいまま", gloss: "dark stays dark, page after page" },
  { romaji: "Keika no Kejime", ja: "経過のけじめ", reading: "けいかのけじめ", gloss: "how it is going, and the line drawn under it" },
  { romaji: "Komakai Buhin", ja: "細かい部品", reading: "こまかいぶひん", gloss: "the small parts a character is made of" },
  { romaji: "Saigo no Ana", ja: "最後の穴", reading: "さいごのあな", gloss: "the last hole in the shelf, filled" },
  { romaji: "Shimesu Ippo", ja: "示す一歩", reading: "しめすいっぽ", gloss: "one step, then the next" },
  { romaji: "Sumizome", ja: "墨染め", reading: "すみぞめ", gloss: "in ink alone, whatever the screen was" },
  { romaji: "Seou Shitaji", ja: "背負う下地", reading: "せおうしたじ", gloss: "the faint ground a stroke is laid on" },
  { romaji: "Somenai Soboku", ja: "染めない素朴", reading: "そめないそぼく", gloss: "undyed and plain, which is what paper wants" },
  { romaji: "Tachimodoru Tanjun", ja: "立ち戻る単純", reading: "たちもどるたんじゅん", gloss: "back to the simple thing" },
  { romaji: "Chotto Hitoiki", ja: "ちょっと一息", reading: "ちょっとひといき", gloss: "a short breath between runs" },
  { romaji: "Tsunde Oku", ja: "摘んでおく", reading: "つんでおく", gloss: "picked as you pass, and kept" },
  { romaji: "Teikei no Tehon", ja: "定型の手本", reading: "ていけいのてほん", gloss: "one header, and every card wears it" },
  { romaji: "Toridasu Tsukuri", ja: "取り出すつくり", reading: "とりだすつくり", gloss: "the parts, taken out and laid down" },
  { romaji: "Nagameru Narabi", ja: "眺める並び", reading: "ながめるならび", gloss: "a row you can look over, leaving none out" },
  { romaji: "Nigiru Ippon", ja: "握る一本", reading: "にぎるいっぽん", gloss: "the one stroke, held on its own" },
  { romaji: "Nugu Kanban", ja: "脱ぐ看板", reading: "ぬぐかんばん", gloss: "the sign the card no longer has to wear" },
  { romaji: "Neru Ichimai", ja: "練る一枚", reading: "ねるいちまい", gloss: "one sheet, to work the character into" },
  { romaji: "Nokoru Usuzumi", ja: "残る薄墨", reading: "のこるうすずみ", gloss: "the faint ink that stays on the page" },
  { romaji: "Hashiru Hitosuji", ja: "走る一筋", reading: "はしるひとすじ", gloss: "a single line, run right through" },
  { romaji: "Hitoshii Yakume", ja: "等しい役目", reading: "ひとしいやくめ", gloss: "the same job everywhere" },
  { romaji: "Fudan no Nanori", ja: "普段の名乗り", reading: "ふだんのなのり", gloss: "introducing itself the way the others do" },
  { romaji: "Hedatenai Masume", ja: "隔てない升目", reading: "へだてないますめ", gloss: "one sheet, no wall between a list and a lone character" },
  { romaji: "Honegumi wa Ugokanai", ja: "骨組みは動かない", reading: "ほねぐみはうごかない", gloss: "the frame stays where it was" },
  { romaji: "Mawaru Madoguchi", ja: "回る窓口", reading: "まわるまどぐち", gloss: "a window you can move around" },
  { romaji: "Miseru Hyouji", ja: "見せる表示", reading: "みせるひょうじ", gloss: "the sheet shows whose it is" },
  { romaji: "Muda naku Mukeru", ja: "無駄なく向ける", reading: "むだなくむける", gloss: "pointed the same way, with nothing built twice" },
  { romaji: "Meguru Mejiri", ja: "巡る目尻", reading: "めぐるめじり", gloss: "the eye comes round to where it asked" },
  { romaji: "Mochiba no Moyori", ja: "持ち場の最寄り", reading: "もちばのもより", gloss: "back to its own post, and near what you asked for" },
  { romaji: "Yajirushi Ryoumuki", ja: "矢印両向き", reading: "やじるしりょうむき", gloss: "an arrow that points both ways" },
  { romaji: "Yukisaki no Yubisasu", ja: "行き先の指差す", reading: "ゆきさきのゆびさす", gloss: "pointing at where you have been" },
  { romaji: "Yomiageru Nedan", ja: "読み上げる値段", reading: "よみあげるねだん", gloss: "the price, read aloud" },
  { romaji: "Rashii Rinkaku", ja: "らしい輪郭", reading: "らしいりんかく", gloss: "an outline that looks like itself" },
  { romaji: "Rittai yori Hiratai", ja: "立体より平たい", reading: "りったいよりひらたい", gloss: "the flat pill, not the raised card" },
  { romaji: "Rui o Yobu", ja: "類を呼ぶ", reading: "るいをよぶ", gloss: "like calls to like" },
  { romaji: "Reigi no Hikigiwa", ja: "礼儀の引き際", reading: "れいぎのひきぎわ", gloss: "knowing when to leave the screen" },
  { romaji: "Rokugatsu no Orime", ja: "六月の折り目", reading: "ろくがつのおりめ", gloss: "every month folded but the one you are in" },
  { romaji: "Wakuni Osamaru", ja: "枠に収まる", reading: "わくにおさまる", gloss: "it sits in the frame it was given" },
  { romaji: "Aiiro no Fudawake", ja: "藍色の札分け", reading: "あいいろのふだわけ", gloss: "sorted by the label it already wore" },
  { romaji: "Ichiba no Isseini", ja: "市場の一斉に", reading: "いちばのいっせいに", gloss: "one market, everyone at once" },
  { romaji: "Utagawanai Tsuzuri", ja: "疑わない綴り", reading: "うたがわないつづり", gloss: "the spelling it takes at its word" },
  { romaji: "Enchou no Meisai", ja: "延長の明細", reading: "えんちょうのめいさい", gloss: "the line item, spelled out at length" },
  { romaji: "Oshinagaki", ja: "お品書き", reading: "おしながき", gloss: "everything on offer, written out" },
  { romaji: "Karita Sakaime", ja: "借りた境目", reading: "かりたさかいめ", gloss: "the borders we borrowed" },
  { romaji: "Kippu no Kihon", ja: "切符の基本", reading: "きっぷのきほん", gloss: "a ticket, and what a ticket is for" },
  { romaji: "Kuuhaku kara Hajimeru", ja: "空白から始める", reading: "くうはくからはじめる", gloss: "starting from a blank row" },
  { romaji: "Kenami Zoroi", ja: "毛並み揃い", reading: "けなみぞろい", gloss: "every chip in the same coat" },
  { romaji: "Kodaina Fuchi", ja: "誇大な縁", reading: "こだいなふち", gloss: "the border that grew with the place" },
  { romaji: "Sarani Sasu", ja: "更に指す", reading: "さらにさす", gloss: "points again, and says what it points at" },
  { romaji: "Shirushita Fukusuukei", ja: "記した複数形", reading: "しるしたふくすうけい", gloss: "the plural written down instead of guessed at" },
  { romaji: "Sunaona Eigo", ja: "素直な英語", reading: "すなおなえいご", gloss: "the English name, plainly, on an English page" },
  { romaji: "Sessuru Kengoto", ja: "接する県ごと", reading: "せっするけんごと", gloss: "a region lit as one shape, not six names in turn" },
  { romaji: "Sokutei no Sokuza", ja: "測定の即座", reading: "そくていのそくざ", gloss: "measured, not guessed at" },
  { romaji: "Tate Ichiretsu", ja: "縦一列", reading: "たていちれつ", gloss: "one column, one weight" },
  { romaji: "Chanto Yomiwake", ja: "ちゃんと読み分け", reading: "ちゃんとよみわけ", gloss: "the reading and the English, told apart" },
  { romaji: "Tsukeru Ashiba", ja: "着ける足場", reading: "つけるあしば", gloss: "a footing to land on, not a sign saying choose" },
  { romaji: "Tekiyou Oboeteiru", ja: "適用覚えている", reading: "てきようおぼえている", gloss: "the settings come back the way you left them" },
  { romaji: "Todokeru Made", ja: "届けるまで", reading: "とどけるまで", gloss: "it keeps trying until the code arrives" },
  { romaji: "Nanoru Kakera", ja: "名乗る欠片", reading: "なのるかけら", gloss: "every piece says what it is called" },
  { romaji: "Nishiki no Hyoushi", ja: "錦の表紙", reading: "にしきのひょうし", gloss: "a proper cover on the page" },
  { romaji: "Nunoji no Monosashi", ja: "布地の物差し", reading: "ぬのじのものさし", gloss: "one ruler, and every piece cut to it" },
  { romaji: "Nerai Doori Tsunagu", ja: "狙い通り繋ぐ", reading: "ねらいどおりつなぐ", gloss: "each title joined to its own page" },
  { romaji: "Nozoita Sawagi", ja: "除いた騒ぎ", reading: "のぞいたさわぎ", gloss: "the noise taken out of the card" },
  { romaji: "Hayai Mitate", ja: "早い見立て", reading: "はやいみたて", gloss: "place the character at a glance" },
  { romaji: "Hiraita Deguchi", ja: "開いた出口", reading: "ひらいたでぐち", gloss: "a way out of every row" },
  { romaji: "Fukumu Chihou", ja: "含む地方", reading: "ふくむちほう", gloss: "the region that holds the place, in its address" },
  { romaji: "Heizen to Nazashi", ja: "平然と名指し", reading: "へいぜんとなざし", gloss: "the sheet plainly named after what is on it" },
  { romaji: "Honyaku Nashi Hikaku", ja: "翻訳なし比較", reading: "ほんやくなしひかく", gloss: "two books on one question, side by side" },
  { romaji: "Matomete Narabete", ja: "まとめて並べて", reading: "まとめてならべて", gloss: "the reading and the English together, when you ask for them" },
  { romaji: "Mitabi Kiku", ja: "三度聞く", reading: "みたびきく", gloss: "ask three times before calling silence a no" },
  { romaji: "Muttsu no Hajimari", ja: "六つの始まり", reading: "むっつのはじまり", gloss: "it begins with six, and climbs from there" },
  { romaji: "Memori no Takasa", ja: "目盛りの高さ", reading: "めもりのたかさ", gloss: "one notch high, held or not" },
  { romaji: "Moto no Homare", ja: "元の誉れ", reading: "もとのほまれ", gloss: "the credit belongs where it came from" },
  { romaji: "Yatto Mannaka", ja: "やっと真ん中", reading: "やっとまんなか", gloss: "in the middle at last" },
  { romaji: "Yutori no Ichijikan", ja: "ゆとりの一時間", reading: "ゆとりのいちじかん", gloss: "an hour's grace, so one answer serves everybody" },
  { romaji: "Yobina no Ita", ja: "呼び名の板", reading: "よびなのいた", gloss: "the board with its own name on it" },
  { romaji: "Rakuna Irodori", ja: "楽な彩り", reading: "らくないろどり", gloss: "colouring that is easy to switch off" },
  { romaji: "Ryouchi no Kokki", ja: "領地の国旗", reading: "りょうちのこっき", gloss: "flags of every land" },
  { romaji: "Rusu no Tsukue", ja: "留守の机", reading: "るすのつくえ", gloss: "the desk left exactly as it was found" },
  { romaji: "Rei no Hitotsumami", ja: "例のひとつまみ", reading: "れいのひとつまみ", gloss: "a pinch of examples" },
  { romaji: "Roken", ja: "露見", reading: "ろけん", gloss: "what was missing, brought to light" },
  { romaji: "Wakemae", ja: "分け前", reading: "わけまえ", gloss: "the share that is the admin's" },
  { romaji: "Arika no Hitomawari", ja: "在り処のひとまわり", reading: "ありかのひとまわり", gloss: "one round of where everything lives" },
  { romaji: "Issho no Sumika", ja: "一緒の住処", reading: "いっしょのすみか", gloss: "the records live where the studying happens" },
  { romaji: "Ubusuna", ja: "産土", reading: "うぶすな", gloss: "the ground you were born on" },
  { romaji: "Eriwake no Me", ja: "選り分けの目", reading: "えりわけのめ", gloss: "an eye for picking out" },
  { romaji: "Oodoori", ja: "大通り", reading: "おおどおり", gloss: "the main street a town is built along" },
  { romaji: "Kaitei no Zenkei", ja: "階梯の全景", reading: "かいていのぜんけい", gloss: "the whole ladder in view" },
  { romaji: "Kiban no Ichidan", ja: "基盤の一段", reading: "きばんのいちだん", gloss: "the first course of the foundation" },
  { romaji: "Kumihimo no Kudan", ja: "組紐の九段", reading: "くみひものくだん", gloss: "a braided cord of nine tiers" },
  { romaji: "Keiryou", ja: "軽量", reading: "けいりょう", gloss: "light to carry: one country at a time" },
  { romaji: "Kodama", ja: "木霊", reading: "こだま", gloss: "an echo: the panel answers the map" },
  { romaji: "Sashikae no Hikae", ja: "差し替えの控え", reading: "さしかえのひかえ", gloss: "a record of the substitutions" },
  { romaji: "Shitagoshirae", ja: "下ごしらえ", reading: "したごしらえ", gloss: "the prep work, done before the cooking" },
  { romaji: "Sumizumi", ja: "隅々", reading: "すみずみ", gloss: "every corner of it, listed again" },
  { romaji: "Seichi no Narashi", ja: "整地のならし", reading: "せいちのならし", gloss: "levelling the ground flat" },
  { romaji: "Sokohe", ja: "其処へ", reading: "そこへ", gloss: "to that very spot, and no other" },
  { romaji: "Tachiyori", ja: "立ち寄り", reading: "たちより", gloss: "a stop along the way, then on to the country you wanted" },
  { romaji: "Chitsujo no Gakunen", ja: "秩序の学年", reading: "ちつじょのがくねん", gloss: "the school year sets the order" },
  { romaji: "Tsumiage no Junjo", ja: "積み上げの順序", reading: "つみあげのじゅんじょ", gloss: "the order things stack in" },
  { romaji: "Tejika na Goi", ja: "手近な語彙", reading: "てぢかなごい", gloss: "the vocabulary closest to hand" },
  { romaji: "Totonoi no Sorezore", ja: "整いのそれぞれ", reading: "ととのいのそれぞれ", gloss: "each one in its place, the set complete" },
  { romaji: "Namiiru", ja: "並み居る", reading: "なみいる", gloss: "all of them gathered, each saying only what it knows" },
  { romaji: "Nidanme no Mikata", ja: "二段目の見方", reading: "にだんめのみかた", gloss: "another way of looking at the rungs" },
  { romaji: "Nurie no Erabi", ja: "塗り絵の選び", reading: "ぬりえのえらび", gloss: "choosing how to colour the same ladder" },
  { romaji: "Nezashi no Meimei", ja: "根ざしの命名", reading: "ねざしのめいめい", gloss: "naming what you are rooted in" },
  { romaji: "nobori", ja: "登り", reading: "のぼり", gloss: "the climb" },
  { romaji: "hashigo", ja: "梯子", reading: "はしご", gloss: "the ladder" },
  { romaji: "Hitonigiri", ja: "一握り", reading: "ひとにぎり", gloss: "a handful to play among the thirty you may read" },
  { romaji: "Fuzoku", ja: "付属", reading: "ふぞく", gloss: "every kanji belonging to the word, the word's own included" },
  { romaji: "Henji", ja: "返事", reading: "へんじ", gloss: "the fuller answer, waiting one tab away" },
  { romaji: "hohaba", ja: "歩幅", reading: "ほはば", gloss: "the length of a stride" },
  { romaji: "maeoki", ja: "前置き", reading: "まえおき", gloss: "the words put in front" },
  { romaji: "mitsukeru", ja: "見つける", reading: "みつける", gloss: "to find it" },
  { romaji: "musubime", ja: "結び目", reading: "むすびめ", gloss: "the knot that ties them" },
  { romaji: "mebae", ja: "芽生え", reading: "めばえ", gloss: "the first shoot" },
  { romaji: "moushikomi", ja: "申し込み", reading: "もうしこみ", gloss: "the application" },
  { romaji: "yakusoku", ja: "約束", reading: "やくそく", gloss: "the promise to come back" },
  { romaji: "yuzuri", ja: "譲り", reading: "ゆずり", gloss: "handed down, not rebuilt" },
  { romaji: "yobiyose", ja: "呼び寄せ", reading: "よびよせ", gloss: "calling it over" },
  { romaji: "raretsu", ja: "羅列", reading: "られつ", gloss: "set out side by side" },
  { romaji: "riyou", ja: "利用", reading: "りよう", gloss: "putting it to use" },
  { romaji: "ruien", ja: "類縁", reading: "るいえん", gloss: "kinship between them" },
  { romaji: "rendou", ja: "連動", reading: "れんどう", gloss: "the two moving together" },
  { romaji: "roteichou", ja: "路程帳", reading: "ろていちょう", gloss: "the log of the route taken" },
  { romaji: "wakegaki", ja: "分け書き", reading: "わけがき", gloss: "set down in parts" },
];
