/**
 * Release codenames, Ubuntu-style but on the gojūon.
 *
 * Each release's version minor walks the 44 usable kana in dictionary order —
 * を is skipped because almost nothing starts with it, and ん because nothing
 * does (our own Shiritori game ends chains on it). After わ the cycle rolls
 * over and the kana repeat with fresh word pairs; a pair itself is never
 * reused, and no word appears twice anywhere in the list — every release's
 * pair is built from words no earlier release used.
 *
 * The codename test pins every entry's reading to its computed kana and
 * requires exactly one entry per shipped version, so a new release must add
 * its name or fail `quality:check`.
 */

export const GOJUON_SEQUENCE = [
  "あ", "い", "う", "え", "お",
  "か", "き", "く", "け", "こ",
  "さ", "し", "す", "せ", "そ",
  "た", "ち", "つ", "て", "と",
  "な", "に", "ぬ", "ね", "の",
  "は", "ひ", "ふ", "へ", "ほ",
  "ま", "み", "む", "め", "も",
  "や", "ゆ", "よ",
  "ら", "り", "る", "れ", "ろ",
  "わ",
] as const;

export type ReleaseCodename = {
  /** Latin rendering shown in the footer. */
  romaji: string;
  /** The name as written, kanji and kana. */
  ja: string;
  /** Full hiragana reading; its first character must match the release's kana. */
  reading: string;
  /** What the name means, for anyone who cannot read the Japanese. */
  gloss: string;
};

export function codenameKanaForMinor(minor: number): { kana: string; cycle: number } {
  const index = (minor - 1) % GOJUON_SEQUENCE.length;
  return { kana: GOJUON_SEQUENCE[index], cycle: Math.floor((minor - 1) / GOJUON_SEQUENCE.length) + 1 };
}

/** Katakana to hiragana, so a name written in katakana still checks its kana. */
export function toHiragana(value: string): string {
  return value.replace(/[ァ-ヶ]/g, (char) =>
    String.fromCharCode(char.charCodeAt(0) - 0x60),
  );
}

/** Index 0 names v0.1.0; a release's codename is CODENAMES[minor - 1]. */
export const CODENAMES: readonly ReleaseCodename[] = [
  { romaji: "Amai Anko", ja: "甘いあんこ", reading: "あまいあんこ", gloss: "sweet red-bean paste" },
  { romaji: "Iki na Izakaya", ja: "粋な居酒屋", reading: "いきないざかや", gloss: "stylish pub" },
  { romaji: "Ureshii Uma", ja: "嬉しい馬", reading: "うれしいうま", gloss: "happy horse" },
  { romaji: "Egao no Enoshima", ja: "笑顔の江ノ島", reading: "えがおのえのしま", gloss: "Enoshima of smiles" },
  { romaji: "Okashi no Oukoku", ja: "お菓子の王国", reading: "おかしのおうこく", gloss: "kingdom of sweets" },
  { romaji: "Kagayaku Kappa", ja: "輝く河童", reading: "かがやくかっぱ", gloss: "gleaming kappa" },
  { romaji: "Kirakira Kitsune", ja: "きらきら狐", reading: "きらきらきつね", gloss: "sparkling fox" },
  { romaji: "Kuroi Kuma", ja: "黒い熊", reading: "くろいくま", gloss: "black bear" },
  { romaji: "Kedakai Kendama", ja: "気高いけん玉", reading: "けだかいけんだま", gloss: "noble kendama" },
  { romaji: "Kogane no Koi", ja: "黄金の鯉", reading: "こがねのこい", gloss: "golden koi" },
  { romaji: "Sakura Samurai", ja: "桜侍", reading: "さくらざむらい", gloss: "cherry-blossom samurai" },
  { romaji: "Shibui Shiba", ja: "渋い柴", reading: "しぶいしば", gloss: "effortlessly cool shiba dog" },
  { romaji: "Suteki na Sushi", ja: "素敵な寿司", reading: "すてきなすし", gloss: "splendid sushi" },
  { romaji: "Sekkachi na Senbei", ja: "せっかちな煎餅", reading: "せっかちなせんべい", gloss: "impatient rice cracker" },
  { romaji: "Sorairo Soba", ja: "空色蕎麦", reading: "そらいろそば", gloss: "sky-blue soba" },
  { romaji: "Tanoshii Tanuki", ja: "楽しい狸", reading: "たのしいたぬき", gloss: "merry tanuki" },
  { romaji: "Chiisana Chouchin", ja: "小さな提灯", reading: "ちいさなちょうちん", gloss: "little paper lantern" },
  { romaji: "Tsuyoi Tsuru", ja: "強い鶴", reading: "つよいつる", gloss: "strong crane" },
  { romaji: "Teruteru Tengu", ja: "てるてる天狗", reading: "てるてるてんぐ", gloss: "shining tengu" },
  { romaji: "Tobikiri Tonkatsu", ja: "とびきりとんかつ", reading: "とびきりとんかつ", gloss: "exceptional pork cutlet" },
  { romaji: "Nagomi Nabe", ja: "和み鍋", reading: "なごみなべ", gloss: "soothing hotpot" },
  { romaji: "Nigiyaka Ninja", ja: "賑やか忍者", reading: "にぎやかにんじゃ", gloss: "boisterous ninja" },
  { romaji: "Nukumori Nurikabe", ja: "ぬくもり塗壁", reading: "ぬくもりぬりかべ", gloss: "warm-hearted wall yokai" },
  { romaji: "Nemui Neko", ja: "眠い猫", reading: "ねむいねこ", gloss: "sleepy cat" },
  { romaji: "Nonbiri Norimaki", ja: "のんびり海苔巻き", reading: "のんびりのりまき", gloss: "easygoing sushi roll" },
  { romaji: "Haikara Hanabi", ja: "ハイカラ花火", reading: "はいからはなび", gloss: "fashionable fireworks" },
  { romaji: "Hikaru Hitsuji", ja: "光る羊", reading: "ひかるひつじ", gloss: "glowing sheep" },
  { romaji: "Fuwafuwa Fuji", ja: "ふわふわ富士", reading: "ふわふわふじ", gloss: "fluffy Mount Fuji" },
  { romaji: "Heiwa na Hebi", ja: "平和な蛇", reading: "へいわなへび", gloss: "peaceful snake" },
  { romaji: "Hokahoka Hotaru", ja: "ほかほか蛍", reading: "ほかほかほたる", gloss: "toasty firefly" },
  { romaji: "Manmaru Matcha", ja: "真ん丸抹茶", reading: "まんまるまっちゃ", gloss: "perfectly round matcha" },
  { romaji: "Midori Miso", ja: "緑味噌", reading: "みどりみそ", gloss: "green miso" },
  { romaji: "Mugen Mugicha", ja: "無限麦茶", reading: "むげんむぎちゃ", gloss: "infinite barley tea" },
  { romaji: "Medetai Melonpan", ja: "めでたいメロンパン", reading: "めでたいめろんぱん", gloss: "auspicious melon bread" },
  { romaji: "Mochimochi Momiji", ja: "もちもち紅葉", reading: "もちもちもみじ", gloss: "springy autumn maple" },
  { romaji: "Yasashii Yatai", ja: "優しい屋台", reading: "やさしいやたい", gloss: "gentle food stall" },
  { romaji: "Yukimi Yuzu", ja: "雪見柚子", reading: "ゆきみゆず", gloss: "snow-viewing yuzu" },
  { romaji: "Yoake Youkai", ja: "夜明け妖怪", reading: "よあけようかい", gloss: "daybreak yokai" },
  { romaji: "Rakuen Ramen", ja: "楽園ラーメン", reading: "らくえんらーめん", gloss: "paradise ramen" },
  { romaji: "Ririshii Ryuu", ja: "凛々しい龍", reading: "りりしいりゅう", gloss: "gallant dragon" },
  { romaji: "Runrun Ruribitaki", ja: "るんるんルリビタキ", reading: "るんるんるりびたき", gloss: "cheerful bluetail bird" },
  { romaji: "Retoro Ressha", ja: "レトロ列車", reading: "れとろれっしゃ", gloss: "retro train" },
  { romaji: "Roman Rousoku", ja: "浪漫蝋燭", reading: "ろまんろうそく", gloss: "romantic candle" },
  { romaji: "Wakuwaku Washi", ja: "わくわく鷲", reading: "わくわくわし", gloss: "excited eagle" },
  { romaji: "Atsuatsu Anmitsu", ja: "熱々あんみつ", reading: "あつあつあんみつ", gloss: "piping-hot anmitsu" },
  { romaji: "Inazuma Inari", ja: "稲妻稲荷", reading: "いなずまいなり", gloss: "lightning inari" },
  { romaji: "Utau Umeboshi", ja: "歌う梅干し", reading: "うたううめぼし", gloss: "singing pickled plum" },
  { romaji: "Enishi no Ema", ja: "縁の絵馬", reading: "えにしのえま", gloss: "votive plaque of destiny" },
  { romaji: "Odoru Onigiri", ja: "踊るおにぎり", reading: "おどるおにぎり", gloss: "dancing rice ball" },
  { romaji: "Kaminari Karaage", ja: "雷唐揚げ", reading: "かみなりからあげ", gloss: "thunder fried chicken" },
  { romaji: "Kinpika Kinkakuji", ja: "金ぴか金閣寺", reading: "きんぴかきんかくじ", gloss: "gleaming Golden Pavilion" },
  { romaji: "Kuishinbou Kujira", ja: "食いしん坊鯨", reading: "くいしんぼうくじら", gloss: "glutton whale" },
  { romaji: "Kenran Keshiki", ja: "絢爛景色", reading: "けんらんけしき", gloss: "dazzling scenery" },
  { romaji: "Kongari Korokke", ja: "こんがりコロッケ", reading: "こんがりころっけ", gloss: "golden-fried croquette" },
  { romaji: "Sawayaka Sashimi", ja: "爽やか刺身", reading: "さわやかさしみ", gloss: "refreshing sashimi" },
  { romaji: "Shinobi Shinkansen", ja: "忍び新幹線", reading: "しのびしんかんせん", gloss: "stealth bullet train" },
  { romaji: "Suzushii Suika", ja: "涼しい西瓜", reading: "すずしいすいか", gloss: "cool watermelon" },
  { romaji: "Seiketsu na Sentou", ja: "清潔な銭湯", reading: "せいけつなせんとう", gloss: "spotless bathhouse" },
  { romaji: "Soyokaze Soumen", ja: "そよ風素麺", reading: "そよかぜそうめん", gloss: "gentle-breeze noodles" },
  { romaji: "Takaramono Taiyaki", ja: "宝物鯛焼き", reading: "たからものたいやき", gloss: "treasure taiyaki" },
  { romaji: "Chikara Chawanmushi", ja: "力茶碗蒸し", reading: "ちからちゃわんむし", gloss: "power egg custard" },
  { romaji: "Tsurutsuru Tsukimi", ja: "つるつる月見", reading: "つるつるつきみ", gloss: "silky moon-viewing" },
  { romaji: "Teppan Tebasaki", ja: "鉄板手羽先", reading: "てっぱんてばさき", gloss: "iron-plate chicken wings" },
  { romaji: "Tokimeki Torii", ja: "ときめき鳥居", reading: "ときめきとりい", gloss: "heart-flutter shrine gate" },
  { romaji: "Natsumatsuri Naruto", ja: "夏祭り鳴門", reading: "なつまつりなると", gloss: "summer-festival whirlpools" },
  { romaji: "Nikoniko Nikujaga", ja: "にこにこ肉じゃが", reading: "にこにこにくじゃが", gloss: "smiling potato stew" },
  { romaji: "Nukazuke Nuigurumi", ja: "糠漬けぬいぐるみ", reading: "ぬかづけぬいぐるみ", gloss: "bran-pickle plushie" },
  { romaji: "Nebuta Nerikiri", ja: "ねぶた練り切り", reading: "ねぶたねりきり", gloss: "festival sweets" },
  { romaji: "Nodoka Noren", ja: "長閑暖簾", reading: "のどかのれん", gloss: "tranquil shop curtain" },
  { romaji: "Harukaze Hanami", ja: "春風花見", reading: "はるかぜはなみ", gloss: "spring-breeze blossom viewing" },
  { romaji: "Hinode Himawari", ja: "日の出向日葵", reading: "ひのでひまわり", gloss: "sunrise sunflower" },
  { romaji: "Fuurin Fukurou", ja: "風鈴梟", reading: "ふうりんふくろう", gloss: "wind-chime owl" },
  { romaji: "Henro Heiya", ja: "遍路平野", reading: "へんろへいや", gloss: "pilgrim plain" },
  { romaji: "Hoshizora Houseki", ja: "星空宝石", reading: "ほしぞらほうせき", gloss: "starry-sky jewel" },
  { romaji: "Maneki Matsuri", ja: "招き祭り", reading: "まねきまつり", gloss: "beckoning festival" },
  { romaji: "Michishio Miyako", ja: "満ち潮都", reading: "みちしおみやこ", gloss: "high-tide capital" },
  { romaji: "Mukashi Musubi", ja: "昔結び", reading: "むかしむすび", gloss: "old-times knot" },
  { romaji: "Megumi Meguri", ja: "恵み巡り", reading: "めぐみめぐり", gloss: "blessing pilgrimage" },
  { romaji: "Momotarou Monaka", ja: "桃太郎最中", reading: "ももたろうもなか", gloss: "Momotaro wafer cake" },
  { romaji: "Yasuragi Yakimochi", ja: "安らぎ焼き餅", reading: "やすらぎやきもち", gloss: "restful grilled rice cake" },
  { romaji: "Yuuyake Yukata", ja: "夕焼け浴衣", reading: "ゆうやけゆかた", gloss: "sunset yukata" },
  { romaji: "Yozakura Yokochou", ja: "夜桜横丁", reading: "よざくらよこちょう", gloss: "night-blossom alley" },
  { romaji: "Rakugaki Ranpu", ja: "落書きランプ", reading: "らくがきらんぷ", gloss: "doodle lamp" },
  { romaji: "Rinrin Ringo", ja: "りんりん林檎", reading: "りんりんりんご", gloss: "chiming apple" },
  { romaji: "Ruriiro Rusuban", ja: "瑠璃色留守番", reading: "るりいろるすばん", gloss: "lapis-blue homewatch" },
  { romaji: "Reimei Renge", ja: "黎明蓮華", reading: "れいめいれんげ", gloss: "dawn lotus" },
  { romaji: "Rojiura Rokuro", ja: "路地裏轆轤", reading: "ろじうらろくろ", gloss: "back-alley potter's wheel" },
  { romaji: "Wagashi Warabimochi", ja: "和菓子蕨餅", reading: "わがしわらびもち", gloss: "sweets and bracken mochi" },
  { romaji: "Aoi Ajisai", ja: "青い紫陽花", reading: "あおいあじさい", gloss: "blue hydrangea" },
  { romaji: "Ichigo Izumi", ja: "苺泉", reading: "いちごいずみ", gloss: "strawberry spring" },
  { romaji: "Ukiyo Uguisu", ja: "浮世鶯", reading: "うきようぐいす", gloss: "floating-world nightingale" },
  { romaji: "Ehon Enpitsu", ja: "絵本鉛筆", reading: "えほんえんぴつ", gloss: "picture-book pencil" },
  { romaji: "Origami Ohagi", ja: "折り紙おはぎ", reading: "おりがみおはぎ", gloss: "origami rice cake" },
  { romaji: "Kaze no Kakigoori", ja: "風のかき氷", reading: "かぜのかきごおり", gloss: "shaved ice on the breeze" },
  { romaji: "Kingyo Kisetsu", ja: "金魚季節", reading: "きんぎょきせつ", gloss: "goldfish season" },
  { romaji: "Kumo no Kurashi", ja: "雲の暮らし", reading: "くものくらし", gloss: "life among clouds" },
  { romaji: "Keiko Biyori", ja: "稽古日和", reading: "けいこびより", gloss: "a fine day to practise" },
  { romaji: "Komorebi Komichi", ja: "木漏れ日小径", reading: "こもれびこみち", gloss: "a lane of dappled sunlight" },
  { romaji: "Satoyama Sanpo", ja: "里山散歩", reading: "さとやまさんぽ", gloss: "a walk through the foothills" },
  { romaji: "Shizukesa Shigure", ja: "静けさ時雨", reading: "しずけさしぐれ", gloss: "the quiet of a passing shower" },
  { romaji: "Suisai Sumire", ja: "水彩菫", reading: "すいさいすみれ", gloss: "a violet in watercolour" },
  { romaji: "Seseragi Semi", ja: "せせらぎ蝉", reading: "せせらぎせみ", gloss: "cicadas over a babbling brook" },
  { romaji: "Soshun Sogen", ja: "早春草原", reading: "そうしゅんそうげん", gloss: "grassland in early spring" },
  { romaji: "Tabi Takibi", ja: "旅焚火", reading: "たびたきび", gloss: "a campfire on the road" },
  { romaji: "Chidori Chaya", ja: "千鳥茶屋", reading: "ちどりちゃや", gloss: "a teahouse where the plovers gather" },
  { romaji: "Tsuyu Tsubame", ja: "梅雨燕", reading: "つゆつばめ", gloss: "swallows in the rainy season" },
  { romaji: "Tegami Tebako", ja: "手紙手箱", reading: "てがみてばこ", gloss: "letters in a keepsake box" },
  { romaji: "Toge no Tomoshibi", ja: "峠の灯", reading: "とうげのともしび", gloss: "a light on the mountain pass" },
  { romaji: "Nanohana Nagisa", ja: "菜の花渚", reading: "なのはななぎさ", gloss: "rape blossoms along the shore" },
  { romaji: "Niji no Niwa", ja: "虹の庭", reading: "にじのにわ", gloss: "a garden under a rainbow" },
  { romaji: "Nukemichi Numa", ja: "抜け道沼", reading: "ぬけみちぬま", gloss: "a shortcut past the marsh" },
  { romaji: "Negai no Neiro", ja: "願いの音色", reading: "ねがいのねいろ", gloss: "the tone of a wish" },
  { romaji: "Nohara no Nozomi", ja: "野原の望み", reading: "のはらののぞみ", gloss: "a wish across the meadow" },
  { romaji: "Hatsuyuki Hiroba", ja: "初雪広場", reading: "はつゆきひろば", gloss: "first snow on the square" },
  { romaji: "Hitoyasumi Hidamari", ja: "一休み日だまり", reading: "ひとやすみひだまり", gloss: "a rest in a patch of sun" },
  { romaji: "Fubuki no Futaba", ja: "吹雪の二葉", reading: "ふぶきのふたば", gloss: "two leaves in a snowstorm" },
  { romaji: "Heya no Hekiga", ja: "部屋の壁画", reading: "へやのへきが", gloss: "a mural in the room" },
  { romaji: "Hoozuki Hosomichi", ja: "鬼灯細道", reading: "ほおずきほそみち", gloss: "a lane of lantern plants" },
  { romaji: "Mado no Maboroshi", ja: "窓の幻", reading: "まどのまぼろし", gloss: "a mirage at the window" },
  { romaji: "Mikazuki Misaki", ja: "三日月岬", reading: "みかづきみさき", gloss: "a crescent moon over the cape" },
  { romaji: "Murasaki no Mukuge", ja: "紫の木槿", reading: "むらさきのむくげ", gloss: "a purple rose of Sharon" },
  { romaji: "Meiro no Mejirushi", ja: "迷路の目印", reading: "めいろのめじるし", gloss: "a landmark in the maze" },
  { romaji: "Mokuren Monogatari", ja: "木蓮物語", reading: "もくれんものがたり", gloss: "a tale told under magnolias" },
  { romaji: "Yanagi no Yuube", ja: "柳の夕べ", reading: "やなぎのゆうべ", gloss: "an evening among willows" },
  { romaji: "Yukidoke Yorimichi", ja: "雪解け寄り道", reading: "ゆきどけよりみち", gloss: "a detour through the thaw" },
  { romaji: "Yonaga no Yoi", ja: "夜長の宵", reading: "よながのよい", gloss: "an evening in the long night" },
  { romaji: "Raimei Rasen", ja: "雷鳴螺旋", reading: "らいめいらせん", gloss: "thunderclap spiral" },
  { romaji: "Rindou Ritsudou", ja: "竜胆律動", reading: "りんどうりつどう", gloss: "the gentian's rhythm" },
  { romaji: "Rurou Ruiseki", ja: "流浪累積", reading: "るろうるいせき", gloss: "what wandering piles up" },
  { romaji: "Renzoku Rekishi", ja: "連続歴史", reading: "れんぞくれきし", gloss: "history, without a gap" },
  { romaji: "Rosen Rokuon", ja: "路線録音", reading: "ろせんろくおん", gloss: "a recording of the route" },
  { romaji: "Wakaba Wadachi", ja: "若葉轍", reading: "わかばわだち", gloss: "new leaves in the wheel ruts" },
  { romaji: "Ashiato Ayatori", ja: "足跡あやとり", reading: "あしあとあやとり", gloss: "footprints in a cat's cradle" },
  { romaji: "Ichiban Inori", ja: "一番祈り", reading: "いちばんいのり", gloss: "the first wish of the day" },
  { romaji: "Uneri Utsuwa", ja: "うねり器", reading: "うねりうつわ", gloss: "a vessel with a swell to it" },
  { romaji: "Emaki Egaku", ja: "絵巻描く", reading: "えまきえがく", gloss: "painting the picture scroll" },
  { romaji: "Ooban Otehon", ja: "大判お手本", reading: "おおばんおてほん", gloss: "large-format copybook" },
  { romaji: "Kami no Kazu", ja: "紙の数", reading: "かみのかず", gloss: "the number of sheets" },
  { romaji: "Kirei na Kyori", ja: "綺麗な距離", reading: "きれいなきょり", gloss: "a clean distance" },
  { romaji: "Kuzurenu Kura", ja: "崩れぬ蔵", reading: "くずれぬくら", gloss: "the storehouse that does not fall" },
  { romaji: "Kengo na Kekkai", ja: "堅固な結界", reading: "けんごなけっかい", gloss: "a solid warding barrier" },
  { romaji: "Kotowaru Kotoba", ja: "断る言葉", reading: "ことわることば", gloss: "words that decline" },
  { romaji: "Saegiru Sakai", ja: "遮る境", reading: "さえぎるさかい", gloss: "the boundary that blocks" },
  { romaji: "Shimaru Shikiri", ja: "締まる仕切り", reading: "しまるしきり", gloss: "the partition that shuts" },
  { romaji: "Sueru Sugata", ja: "据える姿", reading: "すえるすがた", gloss: "the form set in place" },
  { romaji: "Sekimon Seiri", ja: "関門整理", reading: "せきもんせいり", gloss: "tidying the gateways" },
  { romaji: "Soroeru Sotogawa", ja: "揃える外側", reading: "そろえるそとがわ", gloss: "aligning the outside" },
  { romaji: "Tandoku Tabidachi", ja: "単独旅立ち", reading: "たんどくたびだち", gloss: "setting out alone" },
  { romaji: "Chokketsu Chishiki", ja: "直結知識", reading: "ちょっけつちしき", gloss: "knowledge, directly connected" },
  { romaji: "Tsukanda Tsuki", ja: "掴んだ月", reading: "つかんだつき", gloss: "the moon, grasped" },
  { romaji: "Tegaru na Tebiki", ja: "手軽な手引き", reading: "てがるなてびき", gloss: "a handbook made simple" },
  { romaji: "Todoku Toudai", ja: "届く灯台", reading: "とどくとうだい", gloss: "the lighthouse whose light reaches" },
  { romaji: "Nameraka na Nagare", ja: "滑らかな流れ", reading: "なめらかなながれ", gloss: "a smooth flow" },
  { romaji: "Niramu Niou", ja: "睨む仁王", reading: "にらむにおう", gloss: "the glaring temple guardian" },
  { romaji: "Nurikaeta Nuno", ja: "塗り替えた布", reading: "ぬりかえたぬの", gloss: "the cloth, dyed again" },
  { romaji: "Nebaru Nezumi", ja: "粘る鼠", reading: "ねばるねずみ", gloss: "the mouse that holds its ground" },
  { romaji: "Nokotta Noki", ja: "残った軒", reading: "のこったのき", gloss: "the eaves left standing" },
  { romaji: "Hakobu Hako", ja: "運ぶ箱", reading: "はこぶはこ", gloss: "the box that carries" },
  { romaji: "Hiraku Hikidashi", ja: "開く引き出し", reading: "ひらくひきだし", gloss: "the drawer that keeps opening" },
  { romaji: "Fumidasu Fune", ja: "踏み出す舟", reading: "ふみだすふね", gloss: "the boat that sets out" },
  { romaji: "Heiki na Hesaki", ja: "平気な舳先", reading: "へいきなへさき", gloss: "the prow that holds steady" },
  { romaji: "Hokan no Hondana", ja: "保管の本棚", reading: "ほかんのほんだな", gloss: "the shelf that keeps things" },
  { romaji: "Massugu na Machi", ja: "真っ直ぐな街", reading: "まっすぐなまち", gloss: "a street set straight" },
  { romaji: "Mieru Michi", ja: "見える道", reading: "みえるみち", gloss: "a path you can see" },
  { romaji: "Muri no nai Mugi", ja: "無理のない麦", reading: "むりのないむぎ", gloss: "barley that is not forced" },
  { romaji: "Mezasu Meate", ja: "目指す目当て", reading: "めざすめあて", gloss: "the mark you are aiming for" },
  { romaji: "Motto Mokuji", ja: "もっと目次", reading: "もっともくじ", gloss: "more of the table of contents" },
  { romaji: "Yamamori no Yasai", ja: "山盛りの野菜", reading: "やまもりのやさい", gloss: "a heaped plate of vegetables" },
  { romaji: "Yutaka na Yubiwa", ja: "豊かな指輪", reading: "ゆたかなゆびわ", gloss: "a ring with plenty on it" },
  { romaji: "Yosoi no Yohaku", ja: "装いの余白", reading: "よそいのよはく", gloss: "room left in the arrangement" },
  { romaji: "Rakuda no Rashinban", ja: "駱駝の羅針盤", reading: "らくだのらしんばん", gloss: "the camel's compass" },
  { romaji: "Rireki no Ribon", ja: "履歴のリボン", reading: "りれきのりぼん", gloss: "a ribbon of history" },
  { romaji: "Ruri no Ruikei", ja: "瑠璃の類型", reading: "るりのるいけい", gloss: "lapis, sorted by kind" },
  { romaji: "Reisei na Reizouko", ja: "冷静な冷蔵庫", reading: "れいせいなれいぞうこ", gloss: "a refrigerator, keeping its cool" },
  { romaji: "Ronri no Roji", ja: "論理の路地", reading: "ろんりのろじ", gloss: "a lane laid out by reason" },
  { romaji: "Wakeru Wana", ja: "分ける罠", reading: "わけるわな", gloss: "the trap that tells them apart" },
  { romaji: "Arawareru Akari", ja: "現れる灯り", reading: "あらわれるあかり", gloss: "the light that appears" },
  { romaji: "Itsumo no Irikuchi", ja: "いつもの入口", reading: "いつものいりくち", gloss: "the usual way in" },
  { romaji: "Ukeireru Uchi", ja: "受け入れる家", reading: "うけいれるうち", gloss: "the house that takes you in" },
  { romaji: "Erabu Enogu", ja: "選ぶ絵の具", reading: "えらぶえのぐ", gloss: "choosing the right paint" },
  { romaji: "Ooki na Oboegaki", ja: "大きな覚書", reading: "おおきなおぼえがき", gloss: "the large memorandum" },
  { romaji: "Kakikaeru Namae", ja: "書き換える名前", reading: "かきかえるなまえ", gloss: "the name you rewrite" },
  { romaji: "Kizuku Kiroku", ja: "気づく記録", reading: "きづくきろく", gloss: "the record that notices" },
  { romaji: "Kugiru Kukan", ja: "区切る空間", reading: "くぎるくうかん", gloss: "the space that is bounded" },
  { romaji: "Kesshite Kehai", ja: "決して気配", reading: "けっしてけはい", gloss: "the sign that never fades" },
  { romaji: "Kotaeru Kokoro", ja: "答える心", reading: "こたえるこころ", gloss: "the heart that answers back" },
  { romaji: "Sayaka na Iro", ja: "さやかな色", reading: "さやかないろ", gloss: "a colour you can make out clearly" },
  { romaji: "Shirushi no Shikaku", ja: "印の資格", reading: "しるしのしかく", gloss: "the right to wear the badge" },
  { romaji: "Susumu Suji", ja: "進む筋", reading: "すすむすじ", gloss: "a path that leads somewhere" },
  { romaji: "Seiton no Senro", ja: "整頓の線路", reading: "せいとんのせんろ", gloss: "tidied track, all one gauge" },
  { romaji: "Sokojikara no Sora", ja: "底力の空", reading: "そこぢからのそら", gloss: "the sky that holds its strength" },
  { romaji: "Tayori no Tana", ja: "便りの棚", reading: "たよりのたな", gloss: "the shelf where the letters are kept" },
  { romaji: "Chizu no Chikamichi", ja: "地図の近道", reading: "ちずのちかみち", gloss: "the shortcut the map shows" },
  { romaji: "Tsutaeru Tsuchi", ja: "伝える土", reading: "つたえるつち", gloss: "the ground that carries word" },
  { romaji: "Tenohira no Tejun", ja: "手のひらの手順", reading: "てのひらのてじゅん", gloss: "the steps that fit in a palm" },
  { romaji: "Tonari no Tobira", ja: "隣の扉", reading: "となりのとびら", gloss: "the door beside it, and it opens too" },
  { romaji: "Nagai Nagame", ja: "長い眺め", reading: "ながいながめ", gloss: "the long view, every level at once" },
  { romaji: "Nikka no Nimotsu", ja: "日課の荷物", reading: "にっかのにもつ", gloss: "the load one day is allowed to carry" },
  { romaji: "Nukisashi no Nuime", ja: "抜き差しの縫い目", reading: "ぬきさしのぬいめ", gloss: "the seam you can unpick and restitch" },
  { romaji: "Nekko no Nedoko", ja: "根っこの寝床", reading: "ねっこのねどこ", gloss: "a bed for the roots, the first words included" },
  { romaji: "Nobasu Nokogiri", ja: "伸ばす鋸", reading: "のばすのこぎり", gloss: "the saw that reaches further" },
  { romaji: "Hazusanai Hasami", ja: "外さない鋏", reading: "はずさないはさみ", gloss: "the grip that does not slip" },
  { romaji: "Hikikaesu Hyoushiki", ja: "引き返す標識", reading: "ひきかえすひょうしき", gloss: "the sign that sends you back where you were" },
  { romaji: "Fuda ni Fude", ja: "札に筆", reading: "ふだにふで", gloss: "a brush on the label, not a serial number" },
  { romaji: "Heikou na Hedate", ja: "平行な隔て", reading: "へいこうなへだて", gloss: "walls set parallel, every room the same shape" },
  { romaji: "Hodoita Hokorobi", ja: "ほどいた綻び", reading: "ほどいたほころび", gloss: "the seams let out, so nothing is cut off" },
  { romaji: "Matomeru Makura", ja: "まとめる枕", reading: "まとめるまくら", gloss: "the pillow that gathers it all up" },
  { romaji: "Midashi no Mihon", ja: "見出しの見本", reading: "みだしのみほん", gloss: "one heading for every page to go by" },
  { romaji: "Mukaeru Mune", ja: "迎える棟", reading: "むかえるむね", gloss: "the roof that takes you in" },
  { romaji: "Mekutta Meyasu", ja: "めくった目安", reading: "めくっためやす", gloss: "the guide turned face up, no longer folded away" },
  { romaji: "Motomeru Mokuhyou", ja: "求める目標", reading: "もとめるもくひょう", gloss: "the mark you are aiming for" },
  { romaji: "Yane no Aru Yado", ja: "屋根のある宿", reading: "やねのあるやど", gloss: "every lodging with a roof of its own" },
  { romaji: "Yuiitsu no Yubisashi", ja: "唯一の指差し", reading: "ゆいいつのゆびさし", gloss: "one finger pointing, not two" },
  { romaji: "Yokonarabi no Yomi", ja: "横並びの読み", reading: "よこならびのよみ", gloss: "readings set side by side" },
  { romaji: "Raichaku no Basho", ja: "来着の場所", reading: "らいちゃくのばしょ", gloss: "the place you arrive at" },
  { romaji: "Ryouhou Nokosu", ja: "両方残す", reading: "りょうほうのこす", gloss: "it keeps both" },
  { romaji: "Ruuto no Modori", ja: "ルートの戻り", reading: "るーとのもどり", gloss: "the way back along the route" },
  { romaji: "Retsu no Nakami", ja: "列の中身", reading: "れつのなかみ", gloss: "what is inside the row" },
  { romaji: "Rogo no Nafuda", ja: "ロゴの名札", reading: "ろごのなふだ", gloss: "the nameplate on the work" },
  { romaji: "Wakete Naraberu", ja: "分けて並べる", reading: "わけてならべる", gloss: "sorted apart and set out side by side" },
  { romaji: "Arabia no Suuji", ja: "アラビアの数字", reading: "あらびあのすうじ", gloss: "the digits everyone types" },
  { romaji: "Ichiran no Waku", ja: "一覧の枠", reading: "いちらんのわく", gloss: "one frame for every list" },
  { romaji: "Ukabu Uchigawa", ja: "浮かぶ内側", reading: "うかぶうちがわ", gloss: "the inside of a character, surfacing" },
  { romaji: "Eranda Ashimoto", ja: "選んだ足元", reading: "えらんだあしもと", gloss: "one footing, chosen for every card" },
  { romaji: "Onaji Choumen", ja: "同じ帳面", reading: "おなじちょうめん", gloss: "one ledger, kept by everyone" },
  { romaji: "Kazoete Kakunin", ja: "数えて確認", reading: "かぞえてかくにん", gloss: "counted, and checked against its source" },
  { romaji: "Kikoeru Kigou", ja: "聞こえる記号", reading: "きこえるきごう", gloss: "a reading you can hear as well as see" },
  { romaji: "Kunda Junban", ja: "組んだ順番", reading: "くんだじゅんばん", gloss: "the order it was queued in" },
  { romaji: "Keizoku no Kekka", ja: "継続の結果", reading: "けいぞくのけっか", gloss: "what keeping at it adds up to" },
  { romaji: "Koko no Kotae", ja: "個々の答え", reading: "ここのこたえ", gloss: "each thing in its own place" },
  { romaji: "Sashikomu Sou", ja: "差し込む層", reading: "さしこむそう", gloss: "slid into the layer it belongs to" },
  { romaji: "Shizumeta Shihyou", ja: "静めた指標", reading: "しずめたしひょう", gloss: "the target, brought down to size" },
  { romaji: "Sunao na Iriguchi", ja: "素直な入口", reading: "すなおないりぐち", gloss: "an entrance that does what it says" },
  { romaji: "Setsuzoku no Kinjo", ja: "接続の近所", reading: "せつぞくのきんじょ", gloss: "the neighbourhood, joined up" },
  { romaji: "Sonaeta Shotai", ja: "備えた書体", reading: "そなえたしょたい", gloss: "the faces a learner meets, provided" },
  { romaji: "Tabaneta Tegakari", ja: "束ねた手掛かり", reading: "たばねたてがかり", gloss: "the clues, bundled as they are found" },
  { romaji: "Chokusetsu Tadoru", ja: "直接辿る", reading: "ちょくせつたどる", gloss: "reached directly, by its address" },
  { romaji: "Tsunagatta Tochi", ja: "繋がった土地", reading: "つながったとち", gloss: "the land, joined up and read" },
  { romaji: "Tezawari no Haba", ja: "手触りの幅", reading: "てざわりのはば", gloss: "wide enough to reach the column" },
  { romaji: "Toriyoseta Shina", ja: "取り寄せた品", reading: "とりよせたしな", gloss: "the items, gathered as what they are" },
  { romaji: "Nazuketa Juusho", ja: "名付けた住所", reading: "なづけたじゅうしょ", gloss: "an address with a name on it" },
  { romaji: "Nita Mono", ja: "似た物", reading: "にたもの", gloss: "a copy that is yours, or theirs to keep" },
  { romaji: "Nushi ga Kimeru", ja: "主が決める", reading: "ぬしがきめる", gloss: "the owner decides" },
  { romaji: "Nekasete Mamoru", ja: "寝かせて守る", reading: "ねかせてまもる", gloss: "put to rest, and kept for those who hold it" },
  { romaji: "Nokeru Kioku", ja: "除ける記憶", reading: "のけるきおく", gloss: "what you already know, set aside" },
  { romaji: "Hazushite Modoru", ja: "外して戻る", reading: "はずしてもどる", gloss: "taken out, and back where you started" },
  { romaji: "Hiroeru Hibiki", ja: "拾える響き", reading: "ひろえるひびき", gloss: "a sound you can pick up, however you type it" },
  { romaji: "Fueru Mokuroku", ja: "増える目録", reading: "ふえるもくろく", gloss: "a catalogue that keeps itself" },
  { romaji: "Herashite Tsukuru", ja: "減らして作る", reading: "へらしてつくる", gloss: "cut down first, then made" },
  { romaji: "Honno Issatsu", ja: "ほんの一冊", reading: "ほんのいっさつ", gloss: "several lists, just the one volume" },
  { romaji: "Manabu Atsumari", ja: "学ぶ集まり", reading: "まなぶあつまり", gloss: "everything to learn from, gathered in one place" },
  { romaji: "Mittsu Hitotsu", ja: "三つ一つ", reading: "みっつひとつ", gloss: "three ways in, one view" },
  { romaji: "Mukau Saki", ja: "向かう先", reading: "むかうさき", gloss: "somewhere to go, with or without a connection" },
  { romaji: "Medatsu Yobikata", ja: "目立つ呼び方", reading: "めだつよびかた", gloss: "called what it is for" },
  { romaji: "Mou Deta", ja: "もう出た", reading: "もうでた", gloss: "already out, not asked twice" },
  { romaji: "Yasashiku Yomeru", ja: "優しく読める", reading: "やさしくよめる", gloss: "every pill says what it is" },
  { romaji: "Yuruyaka na Soroi", ja: "緩やかな揃い", reading: "ゆるやかなそろい", gloss: "every page in the same clothes" },
  { romaji: "Yosooi wo Awaseru", ja: "装いを合わせる", reading: "よそおいをあわせる", gloss: "the same top on every page" },
  { romaji: "Rakuraku Modoreru", ja: "楽々戻れる", reading: "らくらくもどれる", gloss: "the address brings you back" },
  { romaji: "Rikai shiyasui", ja: "理解しやすい", reading: "りかいしやすい", gloss: "a panel you can actually read" },
  { romaji: "Ruupu de Kakomu", ja: "ループで囲む", reading: "るーぷでかこむ", gloss: "the far islands, framed apart" },
  { romaji: "Renraku Michishirube", ja: "連絡道標", reading: "れんらくみちしるべ", gloss: "an address you can hand to somebody" },
  { romaji: "Rokusen Kazoe", ja: "六線数え", reading: "ろくせんかぞえ", gloss: "counted by the strokes it takes" },
  { romaji: "Wasurenai Katahou", ja: "忘れない片方", reading: "わすれないかたほう", gloss: "a word and its kanji, both kept" },
  { romaji: "Anzan Irazu", ja: "暗算いらず", reading: "あんざんいらず", gloss: "the era year, without the arithmetic" },
  { romaji: "Ima no Souba", ja: "今の相場", reading: "いまのそうば", gloss: "today's rate, in the search box" },
  { romaji: "Umaku Tsunagaru", ja: "うまく繋がる", reading: "うまくつながる", gloss: "your own reviews, brought across" },
  { romaji: "En no Nijuunen", ja: "円の二十年", reading: "えんのにじゅうねん", gloss: "twenty years of the yen, on one line" },
  { romaji: "Oshitsukenai Annai", ja: "押し付けない案内", reading: "おしつけないあんない", gloss: "nothing offered that you cannot open" },
  { romaji: "Kazoku no Kakoi", ja: "家族の囲い", reading: "かぞくのかこい", gloss: "the family's own circle" },
  { romaji: "Kimaru Doru", ja: "決まるドル", reading: "きまるどる", gloss: "which dollar you meant, settled" },
  { romaji: "Kuwaeru Ichigyou", ja: "加える一行", reading: "くわえるいちぎょう", gloss: "one line added above the rows" },
  { romaji: "Kettei Mae no Reberu", ja: "決定前のレベル", reading: "けっていまえのれべる", gloss: "the level before it is settled" },
  { romaji: "Konomi no Kakikata", ja: "好みの書き方", reading: "このみのかきかた", gloss: "a price written the way you write it" },
  { romaji: "Sakanoboru Goukaku", ja: "遡る合格", reading: "さかのぼるごうかく", gloss: "every pass, going back" },
  { romaji: "Shikikin no Keta", ja: "敷金の桁", reading: "しききんのけた", gloss: "the deposit read at the right number of zeros" },
  { romaji: "Sugu Wakaru Yurai", ja: "すぐ分かる由来", reading: "すぐわかるゆらい", gloss: "where a list came from, at a glance" },
  { romaji: "Seiretsu Naoshi", ja: "整列直し", reading: "せいれつなおし", gloss: "the facts line up where they belong" },
  { romaji: "Sonaeru Bushu", ja: "備える部首", reading: "そなえるぶしゅ", gloss: "the radicals a character is made ready from" },
  { romaji: "Tatta Hitokoto", ja: "たった一言", reading: "たったひとこと", gloss: "one line saying why it is here" },
  { romaji: "Chuumon no Kensaku", ja: "注文の検索", reading: "ちゅうもんのけんさく", gloss: "the search you type as a command" },
  { romaji: "Tsumete Narabu", ja: "詰めて並ぶ", reading: "つめてならぶ", gloss: "the grid packed into fewer rows" },
  { romaji: "Temoto Techou", ja: "手元手帳", reading: "てもとてちょう", gloss: "the notebook kept at hand" },
  { romaji: "Touitsu no Ookisa", ja: "統一の大きさ", reading: "とういつのおおきさ", gloss: "one size for both search boxes" },
  { romaji: "Nazoru Katachi", ja: "なぞる形", reading: "なぞるかたち", gloss: "a shape traced for every radical" },
  { romaji: "Nihongo Igai", ja: "日本語以外", reading: "にほんごいがい", gloss: "a radical named in English too" },
  { romaji: "Nukete Hirogaru", ja: "抜けて広がる", reading: "ぬけてひろがる", gloss: "the links step out and the box widens" },
  { romaji: "Nebari no Bangou", ja: "粘りの番号", reading: "ねばりのばんごう", gloss: "the numbers you can finally stay with" },
  { romaji: "Nozoku Botan", ja: "覗くボタン", reading: "のぞくぼたん", gloss: "the button that waits until you look" },
  { romaji: "Hanareru Aida", ja: "離れる間", reading: "はなれるあいだ", gloss: "the space that opens between the numbers" },
  { romaji: "Hitofude Hanshi", ja: "一筆半紙", reading: "ひとふではんし", gloss: "a single brushstroke on writing paper" },
  { romaji: "Futatsu Hikaeru", ja: "二つ控える", reading: "ふたつひかえる", gloss: "the two sections that stand aside" },
  { romaji: "Hen na Ten", ja: "変な点", reading: "へんなてん", gloss: "the dot that was reading as a break" },
  { romaji: "Hoshii Meibo", ja: "欲しい名簿", reading: "ほしいめいぼ", gloss: "the list you wanted to see" },
  { romaji: "Mataseru Owari", ja: "待たせる終わり", reading: "またせるおわり", gloss: "the end of being kept waiting" },
  { romaji: "Mitorizu no Machikado", ja: "見取り図の街角", reading: "みとりずのまちかど", gloss: "a street corner with a map on it" },
  { romaji: "Musubu Shiori", ja: "結ぶ栞", reading: "むすぶしおり", gloss: "the list, tied to what it means" },
  { romaji: "Mekuranai Mekata", ja: "めくらない目方", reading: "めくらないめかた", gloss: "weighed without turning a page" },
  { romaji: "Mochikaeru Tsuika", ja: "\u6301\u3061\u5e30\u308b\u8ffd\u52a0", reading: "\u3082\u3061\u304b\u3048\u308b\u3064\u3044\u304b", gloss: "the additions you take home from the original" },
  { romaji: "Yamu Chiratsuki", ja: "止むちらつき", reading: "やむちらつき", gloss: "the flicker that stops" },
  { romaji: "Yuruganai Hyoumen", ja: "揺るがない表面", reading: "ゆるがないひょうめん", gloss: "a surface that does not shift" },
  { romaji: "Yosoou Hitokumi", ja: "装う一組", reading: "よそおうひとくみ", gloss: "one set, dressed alike" },
  { romaji: "Raihou", ja: "来訪", reading: "らいほう", gloss: "a visit, calling on somebody else" },
  { romaji: "Rinsho no Ikkaku", ja: "臨書の一画", reading: "りんしょのいっかく", gloss: "one stroke of the model you are copying" },
  { romaji: "Ruiji no Ruisui", ja: "類似の類推", reading: "るいじのるいすい", gloss: "inferring one link from another because they look alike" },
  { romaji: "Rekkyo", ja: "列挙", reading: "れっきょ", gloss: "listing things out, one page at a time" },
  { romaji: "Rouka no Isshitsu", ja: "廊下の一室", reading: "ろうかのいっしつ", gloss: "one room off the corridor, with a door of its own" },
  { romaji: "Watasu Tanomi", ja: "渡す頼み", reading: "わたすたのみ", gloss: "the request, handed across" },
  { romaji: "Akeru Aikagi", ja: "開ける合鍵", reading: "あけるあいかぎ", gloss: "one spare key, and it opens all three" },
  { romaji: "Ireru Ibasho", ja: "入れる居場所", reading: "いれるいばしょ", gloss: "the place to put it, from where you found it" },
  { romaji: "Uketoru Bun Dake", ja: "受け取る分だけ", reading: "うけとるぶんだけ", gloss: "only the part you take" },
  { romaji: "Eru Atesaki", ja: "得る宛先", reading: "えるあてさき", gloss: "the address it actually reaches" },
  { romaji: "Otagai no Oboe", ja: "お互いの覚え", reading: "おたがいのおぼえ", gloss: "what each other has learned" },
  { romaji: "Kaeseru Kirikae", ja: "返せる切り替え", reading: "かえせるきりかえ", gloss: "a switch that goes back" },
  { romaji: "Kikanai Kariban", ja: "聞かない仮番", reading: "きかないかりばん", gloss: "the stand-in it stops asking about" },
  { romaji: "Kurai Mama", ja: "暗いまま", reading: "くらいまま", gloss: "dark stays dark, page after page" },
  { romaji: "Keika no Kejime", ja: "経過のけじめ", reading: "けいかのけじめ", gloss: "how it is going, and the line drawn under it" },
  { romaji: "Komakai Buhin", ja: "細かい部品", reading: "こまかいぶひん", gloss: "the small parts a character is made of" },
  { romaji: "Saigo no Ana", ja: "最後の穴", reading: "さいごのあな", gloss: "the last hole in the shelf, filled" },
  { romaji: "Shimesu Ippo", ja: "示す一歩", reading: "しめすいっぽ", gloss: "one step, then the next" },
  { romaji: "Sumizome", ja: "墨染め", reading: "すみぞめ", gloss: "in ink alone, whatever the screen was" },
  { romaji: "Seou Shitaji", ja: "背負う下地", reading: "せおうしたじ", gloss: "the faint ground a stroke is laid on" },
  { romaji: "Somenai Soboku", ja: "染めない素朴", reading: "そめないそぼく", gloss: "undyed and plain, which is what paper wants" },
  { romaji: "Tachimodoru Tanjun", ja: "立ち戻る単純", reading: "たちもどるたんじゅん", gloss: "back to the simple thing" },
  { romaji: "Chotto Hitoiki", ja: "ちょっと一息", reading: "ちょっとひといき", gloss: "a short breath between runs" },
  { romaji: "Tsunde Oku", ja: "摘んでおく", reading: "つんでおく", gloss: "picked as you pass, and kept" },
  { romaji: "Teikei no Tehon", ja: "定型の手本", reading: "ていけいのてほん", gloss: "one header, and every card wears it" },
  { romaji: "Toridasu Tsukuri", ja: "取り出すつくり", reading: "とりだすつくり", gloss: "the parts, taken out and laid down" },
  { romaji: "Nagameru Narabi", ja: "眺める並び", reading: "ながめるならび", gloss: "a row you can look over, leaving none out" },
  { romaji: "Nigiru Ippon", ja: "握る一本", reading: "にぎるいっぽん", gloss: "the one stroke, held on its own" },
  { romaji: "Nugu Kanban", ja: "脱ぐ看板", reading: "ぬぐかんばん", gloss: "the sign the card no longer has to wear" },
  { romaji: "Neru Ichimai", ja: "練る一枚", reading: "ねるいちまい", gloss: "one sheet, to work the character into" },
  { romaji: "Nokoru Usuzumi", ja: "残る薄墨", reading: "のこるうすずみ", gloss: "the faint ink that stays on the page" },
  { romaji: "Hashiru Hitosuji", ja: "走る一筋", reading: "はしるひとすじ", gloss: "a single line, run right through" },
  { romaji: "Hitoshii Yakume", ja: "等しい役目", reading: "ひとしいやくめ", gloss: "the same job everywhere" },
  { romaji: "Fudan no Nanori", ja: "普段の名乗り", reading: "ふだんのなのり", gloss: "introducing itself the way the others do" },
  { romaji: "Hedatenai Masume", ja: "隔てない升目", reading: "へだてないますめ", gloss: "one sheet, no wall between a list and a lone character" },
  { romaji: "Honegumi wa Ugokanai", ja: "骨組みは動かない", reading: "ほねぐみはうごかない", gloss: "the frame stays where it was" },
  { romaji: "Mawaru Madoguchi", ja: "回る窓口", reading: "まわるまどぐち", gloss: "a window you can move around" },
  { romaji: "Miseru Hyouji", ja: "見せる表示", reading: "みせるひょうじ", gloss: "the sheet shows whose it is" },
  { romaji: "Muda naku Mukeru", ja: "無駄なく向ける", reading: "むだなくむける", gloss: "pointed the same way, with nothing built twice" },
  { romaji: "Meguru Mejiri", ja: "巡る目尻", reading: "めぐるめじり", gloss: "the eye comes round to where it asked" },
  { romaji: "Mochiba no Moyori", ja: "持ち場の最寄り", reading: "もちばのもより", gloss: "back to its own post, and near what you asked for" },
  { romaji: "Yajirushi Ryoumuki", ja: "矢印両向き", reading: "やじるしりょうむき", gloss: "an arrow that points both ways" },
  { romaji: "Yukisaki no Yubisasu", ja: "行き先の指差す", reading: "ゆきさきのゆびさす", gloss: "pointing at where you have been" },
  { romaji: "Yomiageru Nedan", ja: "読み上げる値段", reading: "よみあげるねだん", gloss: "the price, read aloud" },
  { romaji: "Rashii Rinkaku", ja: "らしい輪郭", reading: "らしいりんかく", gloss: "an outline that looks like itself" },
  { romaji: "Rittai yori Hiratai", ja: "立体より平たい", reading: "りったいよりひらたい", gloss: "the flat pill, not the raised card" },
  { romaji: "Rui o Yobu", ja: "類を呼ぶ", reading: "るいをよぶ", gloss: "like calls to like" },
  { romaji: "Reigi no Hikigiwa", ja: "礼儀の引き際", reading: "れいぎのひきぎわ", gloss: "knowing when to leave the screen" },
  { romaji: "Rokugatsu no Orime", ja: "六月の折り目", reading: "ろくがつのおりめ", gloss: "every month folded but the one you are in" },
  { romaji: "Wakuni Osamaru", ja: "枠に収まる", reading: "わくにおさまる", gloss: "it sits in the frame it was given" },
  { romaji: "Aiiro no Fudawake", ja: "藍色の札分け", reading: "あいいろのふだわけ", gloss: "sorted by the label it already wore" },
  { romaji: "Ichiba no Isseini", ja: "市場の一斉に", reading: "いちばのいっせいに", gloss: "one market, everyone at once" },
  { romaji: "Utagawanai Tsuzuri", ja: "疑わない綴り", reading: "うたがわないつづり", gloss: "the spelling it takes at its word" },
  { romaji: "Enchou no Meisai", ja: "延長の明細", reading: "えんちょうのめいさい", gloss: "the line item, spelled out at length" },
  { romaji: "Oshinagaki", ja: "お品書き", reading: "おしながき", gloss: "everything on offer, written out" },
  { romaji: "Karita Sakaime", ja: "借りた境目", reading: "かりたさかいめ", gloss: "the borders we borrowed" },
  { romaji: "Kippu no Kihon", ja: "切符の基本", reading: "きっぷのきほん", gloss: "a ticket, and what a ticket is for" },
  { romaji: "Kuuhaku kara Hajimeru", ja: "空白から始める", reading: "くうはくからはじめる", gloss: "starting from a blank row" },
  { romaji: "Kenami Zoroi", ja: "毛並み揃い", reading: "けなみぞろい", gloss: "every chip in the same coat" },
  { romaji: "Kodaina Fuchi", ja: "誇大な縁", reading: "こだいなふち", gloss: "the border that grew with the place" },
  { romaji: "Sarani Sasu", ja: "更に指す", reading: "さらにさす", gloss: "points again, and says what it points at" },
  { romaji: "Shirushita Fukusuukei", ja: "記した複数形", reading: "しるしたふくすうけい", gloss: "the plural written down instead of guessed at" },
  { romaji: "Sunaona Eigo", ja: "素直な英語", reading: "すなおなえいご", gloss: "the English name, plainly, on an English page" },
  { romaji: "Sessuru Kengoto", ja: "接する県ごと", reading: "せっするけんごと", gloss: "a region lit as one shape, not six names in turn" },
  { romaji: "Sokutei no Sokuza", ja: "測定の即座", reading: "そくていのそくざ", gloss: "measured, not guessed at" },
  { romaji: "Tate Ichiretsu", ja: "縦一列", reading: "たていちれつ", gloss: "one column, one weight" },
  { romaji: "Chanto Yomiwake", ja: "ちゃんと読み分け", reading: "ちゃんとよみわけ", gloss: "the reading and the English, told apart" },
  { romaji: "Tsukeru Ashiba", ja: "着ける足場", reading: "つけるあしば", gloss: "a footing to land on, not a sign saying choose" },
  { romaji: "Tekiyou Oboeteiru", ja: "適用覚えている", reading: "てきようおぼえている", gloss: "the settings come back the way you left them" },
  { romaji: "Todokeru Made", ja: "届けるまで", reading: "とどけるまで", gloss: "it keeps trying until the code arrives" },
  { romaji: "Nanoru Kakera", ja: "名乗る欠片", reading: "なのるかけら", gloss: "every piece says what it is called" },
  { romaji: "Nishiki no Hyoushi", ja: "錦の表紙", reading: "にしきのひょうし", gloss: "a proper cover on the page" },
  { romaji: "Nunoji no Monosashi", ja: "布地の物差し", reading: "ぬのじのものさし", gloss: "one ruler, and every piece cut to it" },
  { romaji: "Nerai Doori Tsunagu", ja: "狙い通り繋ぐ", reading: "ねらいどおりつなぐ", gloss: "each title joined to its own page" },
  { romaji: "Nozoita Sawagi", ja: "除いた騒ぎ", reading: "のぞいたさわぎ", gloss: "the noise taken out of the card" },
  { romaji: "Hayai Mitate", ja: "早い見立て", reading: "はやいみたて", gloss: "place the character at a glance" },
  { romaji: "Hiraita Deguchi", ja: "開いた出口", reading: "ひらいたでぐち", gloss: "a way out of every row" },
  { romaji: "Fukumu Chihou", ja: "含む地方", reading: "ふくむちほう", gloss: "the region that holds the place, in its address" },
  { romaji: "Heizen to Nazashi", ja: "平然と名指し", reading: "へいぜんとなざし", gloss: "the sheet plainly named after what is on it" },
  { romaji: "Honyaku Nashi Hikaku", ja: "翻訳なし比較", reading: "ほんやくなしひかく", gloss: "two books on one question, side by side" },
];

/**
 * The kanji form worth printing beside the reading, or `null` when the name is
 * already written in kana and showing both would just repeat it.
 */
export function codenameKanji(codename: ReleaseCodename): string | null {
  return codename.ja === codename.reading ? null : codename.ja;
}

export function codenameForMinor(minor: number): ReleaseCodename | null {
  return CODENAMES[minor - 1] ?? null;
}

export function codenameForVersion(version: string): ReleaseCodename | null {
  const minor = Number(version.split(".")[1]);
  return Number.isFinite(minor) ? codenameForMinor(minor) : null;
}
