import type { ReleaseCodename } from "./releaseCodenames";

/** Releases 441 to 486. See `releaseCodenameList.ts`. */
export const CODENAMES_PART_3: readonly ReleaseCodename[] = [
  { romaji: "ayumi", ja: "歩み", reading: "あゆみ", gloss: "the pace of the walk" },
  { romaji: "ikioi", ja: "勢い", reading: "いきおい", gloss: "the momentum it builds" },
  { romaji: "udemae", ja: "腕前", reading: "うでまえ", gloss: "how good you have got" },
  { romaji: "edaha", ja: "枝葉", reading: "えだは", gloss: "the branches and leaves of it" },
  { romaji: "ooyake", ja: "公", reading: "おおやけ", gloss: "made official" },
  { romaji: "kagen", ja: "加減", reading: "かげん", gloss: "the right amount of it" },
  { romaji: "kizashi", ja: "兆し", reading: "きざし", gloss: "the first sign of what you know" },
  { romaji: "kumitate", ja: "組み立て", reading: "くみたて", gloss: "putting the pieces together" },
  { romaji: "kesseki", ja: "欠席", reading: "けっせき", gloss: "the absence, accounted for" },
  { romaji: "kokorozashi", ja: "志", reading: "こころざし", gloss: "the day's resolve" },
  { romaji: "saiten", ja: "採点", reading: "さいてん", gloss: "the tally" },
  { romaji: "shikumi", ja: "仕組み", reading: "しくみ", gloss: "how the mechanism runs" },
  { romaji: "sudeni", ja: "既に", reading: "すでに", gloss: "already known before you came" },
  { romaji: "sebone", ja: "背骨", reading: "せぼね", gloss: "the backbone of the gate" },
  { romaji: "sonaetsuke", ja: "備え付け", reading: "そなえつけ", gloss: "the fittings, adjustable" },
  { romaji: "tazuna", ja: "手綱", reading: "たづな", gloss: "the reins, in your hands" },
  { romaji: "chouwa", ja: "調和", reading: "ちょうわ", gloss: "set to suit you" },
  { romaji: "Tsui no Kanji", ja: "対の漢字", reading: "ついのかんじ", gloss: "the character that has a twin" },
  { romaji: "Temae no Keikoku", ja: "手前の警告", reading: "てまえのけいこく", gloss: "the warning that comes before the mistake" },
  { romaji: "torikime", ja: "取り決め", reading: "とりきめ", gloss: "the rules, kept" },
  { romaji: "Naosu Medama", ja: "直す目玉", reading: "なおすめだま", gloss: "the markers you answer with, put back" },
  { romaji: "Nigeta Moji", ja: "逃げた文字", reading: "にげたもじ", gloss: "the characters that got away" },
  { romaji: "Nukarinai Shiken", ja: "抜かりない試験", reading: "ぬかりないしけん", gloss: "a test with nothing missed" },
  { romaji: "Nefuda no Kimari", ja: "値札の決まり", reading: "ねふだのきまり", gloss: "one rule for every chip's tag" },
  { romaji: "Nobiru Keikenchi", ja: "伸びる経験値", reading: "のびるけいけんち", gloss: "experience that grows on either feed" },
  { romaji: "Hashiwatashi", ja: "橋渡し", reading: "はしわたし", gloss: "a review that crosses to WaniKani" },
  { romaji: "Hitotsuzuki no Fukushuu", ja: "一続きの復習", reading: "ひとつづきのふくしゅう", gloss: "one unbroken review, whichever feed" },
  { romaji: "Fukkyuu no Asa", ja: "復旧の朝", reading: "ふっきゅうのあさ", gloss: "the morning it came back" },
  { romaji: "Henka no Kizuki", ja: "変化の気づき", reading: "へんかのきづき", gloss: "noticing what the answer changed" },
  { romaji: "Hodoku Kijutsu", ja: "解く記述", reading: "ほどくきじゅつ", gloss: "the description untangled from the code" },
  { romaji: "Manabi no Mochimono", ja: "学びの持ち物", reading: "まなびのもちもの", gloss: "the numbers you carry" },
  { romaji: "Mitooshi no Dan", ja: "見通しの段", reading: "みとおしのだん", gloss: "the rung you can see ahead" },
  { romaji: "Muchuu no Suuchi", ja: "夢中の数値", reading: "むちゅうのすうち", gloss: "the figure you keep checking" },
  { romaji: "Mekuru Kata", ja: "めくる形", reading: "めくるかた", gloss: "the shape you turn over" },
  { romaji: "Moreta Kakikae", ja: "漏れた書き換え", reading: "もれたかきかえ", gloss: "the rewrite that slipped through" },
  { romaji: "Yadoru Aidagara", ja: "宿る間柄", reading: "やどるあいだがら", gloss: "the kinship between the two names" },
  { romaji: "Yuzuru Honmyou", ja: "譲る本名", reading: "ゆずるほんみょう", gloss: "the true name, given back" },
  { romaji: "Yosomichi no Shuusoku", ja: "余所道の収束", reading: "よそみちのしゅうそく", gloss: "the second path folded into the first" },
  { romaji: "Rakan no Minamoto", ja: "羅漢の源", reading: "らかんのみなもと", gloss: "the single source everything reads" },
  { romaji: "Ribetsu shita Ran", ja: "離別した欄", reading: "りべつしたらん", gloss: "the panel that took its leave" },
  { romaji: "Ruibetsu no Aoiro", ja: "類別の青色", reading: "るいべつのあおいろ", gloss: "the blue that sorts them" },
  { romaji: "Renkei suru Katagata", ja: "連携する方々", reading: "れんけいするかたがた", gloss: "each side named by the other" },
  { romaji: "Rousaku no Jibun", ja: "労作の自分", reading: "ろうさくのじぶん", gloss: "words of its own making" },
  { romaji: "Wakachi no Shuukei", ja: "分かちの集計", reading: "わかちのしゅうけい", gloss: "the two counted apart" },
  { romaji: "Ariau Dankai", ja: "在り合う段階", reading: "ありあうだんかい", gloss: "the levels that are actually there" },
  { romaji: "Ikkatsu no Nokori", ja: "一括の残り", reading: "いっかつののこり", gloss: "what is left, at a glance" },
  { romaji: "Uchiwake no Meihyou", ja: "内訳の名標", reading: "うちわけのめいひょう", gloss: "the label that says which" },
  { romaji: "Enjiru Kaidan", ja: "演じる階段", reading: "えんじるかいだん", gloss: "the staircase, playing its part" },
  { romaji: "Okonau Bunrui", ja: "行う分類", reading: "おこなうぶんるい", gloss: "sorted by what you are doing" },
  { romaji: "Kaeru Kikan", ja: "変える期間", reading: "かえるきかん", gloss: "the span that changed" },
  { romaji: "Kigen no Toikake", ja: "期限の問いかけ", reading: "きげんのといかけ", gloss: "the question of which deadline" },
  { romaji: "Kugiri no Michisuji", ja: "区切りの道筋", reading: "くぎりのみちすじ", gloss: "a route cut into clean sections" },
  { romaji: "Kensa no Keiro", ja: "検査の経路", reading: "けんさのけいろ", gloss: "a route you can inspect" },
  { romaji: "Konseki no Koyomi", ja: "痕跡の暦", reading: "こんせきのこよみ", gloss: "a calendar of what was answered when" },
  { romaji: "Sasayaka na Shomei", ja: "ささやかな署名", reading: "ささやかなしょめい", gloss: "a small signature on the work" },
  { romaji: "Shinme no Kotodama", ja: "新芽の言霊", reading: "しんめのことだま", gloss: "the words a shoot is named with" },
  { romaji: "Sujimichi no Yurushi", ja: "筋道の許し", reading: "すじみちのゆるし", gloss: "the reasoning, allowed through" },
  { romaji: "Sekkei no Sujigaki", ja: "設計の筋書き", reading: "せっけいのすじがき", gloss: "the plan the design follows" },
  { romaji: "Sonzai no Aratana", ja: "存在の新たな", reading: "そんざいのあらたな", gloss: "the same thing, newly named" },
  { romaji: "Tadaima no Houbi", ja: "ただいまの褒美", reading: "ただいまのほうび", gloss: "the reward, right now" },
  { romaji: "Chigai no Irowake", ja: "違いの色分け", reading: "ちがいのいろわけ", gloss: "the difference, sorted by colour" },
  { romaji: "Tsumikasane no Furui", ja: "積み重ねの篩", reading: "つみかさねのふるい", gloss: "a sieve over what has been built up" },
  { romaji: "Tekagami no Futayomi", ja: "手鏡の二読み", reading: "てかがみのふたよみ", gloss: "both readings, held up side by side" },
  { romaji: "Tozan no Danchigai", ja: "登山の段違い", reading: "とざんのだんちがい", gloss: "the climb, and whose steps you are counting" },
  { romaji: "Naifu no Kirikuchi", ja: "ナイフの切り口", reading: "ないふのきりくち", gloss: "the cut, and what it opens" },
  { romaji: "Niawase no Hitomatome", ja: "荷合わせの一纏め", reading: "にあわせのひとまとめ", gloss: "the whole load, taken at once" },
  { romaji: "Nuguisari no Kazari", ja: "拭い去りの飾り", reading: "ぬぐいさりのかざり", gloss: "the ornament wiped away" },
  { romaji: "Nezuki no Sunpou", ja: "根付きの寸法", reading: "ねづきのすんぽう", gloss: "the measure that stays put" },
  { romaji: "Norikoeru Shirase", ja: "乗り越える知らせ", reading: "のりこえるしらせ", gloss: "word of what you got past" },
  { romaji: "Haridashita Kuraidori", ja: "貼り出した位取り", reading: "はりだしたくらいどり", gloss: "your ranking, put up where you can see it" },
  { romaji: "Hibiku Koe", ja: "響く声", reading: "ひびくこえ", gloss: "the voice that carries" },
  { romaji: "Fusegu Kamae", ja: "防ぐ構え", reading: "ふせぐかまえ", gloss: "the stance that prevents it" },
  { romaji: "Hedataru Jiban", ja: "隔たる地盤", reading: "へだたるじばん", gloss: "ground that no longer drifts apart" },
  { romaji: "Honsuji no Juni", ja: "本筋の順位", reading: "ほんすじのじゅんい", gloss: "the placing on the main line" },
  { romaji: "Matomatta Tsuranari", ja: "纏まった連なり", reading: "まとまったつらなり", gloss: "the run that was brought together" },
  { romaji: "Mitoosi Tadori", ja: "見通し辿り", reading: "みとおしたどり", gloss: "following the record back" },
  { romaji: "Mudanonai Haichi", ja: "無駄のない配置", reading: "むだのないはいち", gloss: "the arrangement with nothing wasted" },
  { romaji: "Medo no Karusa", ja: "目処の軽さ", reading: "めどのかるさ", gloss: "the lightness of a clear view ahead" },
  { romaji: "Motome Dodai", ja: "求め土台", reading: "もとめどだい", gloss: "the footing you were after" },
  { romaji: "Yaridashi Meikaku", ja: "遣り出し明確", reading: "やりだしめいかく", gloss: "what it pays, said plainly" },
  { romaji: "Yudaneta Isshuu", ja: "委ねた一週", reading: "ゆだねたいっしゅう", gloss: "the week you were given" },
];
