import type { LevelItem } from "../../explorerTypes";
import type { VocabularyKanjiLink } from "../lib/levelExplorerItemDetails";

export type LevelExplorerItemsGridProps = {
  accountId: string;
  filteredItems: LevelItem[];
  visibleItems: LevelItem[];
  selectedItem: LevelItem | null;
  visibleDetailInsertIndex: number;
  selectedLevelList: number[];
  studyMode: boolean;
  showEnglish: boolean;
  canToggleEnglish: boolean;
  isPeekRevealed: boolean;
  selectedMeaningExplanation: string;
  selectedReadingExplanationRaw: string;
  showReadingExplanation: boolean;
  hasPrimaryRelatedPanel: boolean;
  hasVisuallySimilarPanel: boolean;
  hasUsedInVocabularyPanel: boolean;
  vocabularyKanjiLinks: VocabularyKanjiLink[];
  subjectById: Map<number, LevelItem>;
  selectedSubjectIds: Set<number>;
  isResetting: boolean;
  resetFeedback: { kind: "success" | "error"; message: string } | null;
  recentOnly: boolean;
  showLocked: boolean;
  allowHideLocked: boolean;
  sentinelRef: React.RefObject<HTMLDivElement | null>;
  onClearFilters: () => void;
  onSelectItem: (subjectId: number) => void;
  onTogglePeek: (subjectId: number) => void;
  onSetRecentOnly: (next: boolean) => void;
  onSetShowLocked: (next: boolean) => void;
  onToggleShowEnglish: () => void;
  onToggleSubjectSelection: (subjectId: number) => void;
  onSelectSubjectIds: (subjectIds: number[]) => void;
  onSelectVisibleSubjects: () => void;
  onClearSelection: () => void;
  onResetSelected: () => void;
  onResetSingle: (subjectId: number) => void;
  onJumpToRelatedSubject: (subjectId: number, targetLevel?: number | null) => Promise<void>;
  onJumpToKanji: (subjectId: number, wkLevel: number | null) => Promise<void>;
};
