/**
 * The Next.js ambient types, committed.
 *
 * `next-env.d.ts` carries these same references but is gitignored and
 * generated by the dev server, so a fresh checkout — CI running the
 * typecheck gate — does not have it and every `@/images/*.png` import
 * fails with TS2307. This file is the committed half: only the package
 * references, without next-env's import of generated `.next/` route types.
 */

/// <reference types="next" />
/// <reference types="next/image-types/global" />
