import { NextResponse } from "next/server";

import { fetchAdminContentSources } from "@/lib/adminContentSources";
import { isAuthorizedAdmin } from "@/lib/admin";
import { withApiRouteTelemetry } from "@/lib/apiRouteTelemetry";

/**
 * The state of the school-grade and map content.
 *
 * Both begin as files in the repo, and the admin had no way to see whether
 * what shipped matches what is loaded - grades are seeded into the database by
 * a script that has to be remembered, maps are generated by another.
 */
export async function GET(request: Request) {
  return withApiRouteTelemetry({
    route: "/api/admin/content-sources",
    method: "GET",
    request,
    execute: async () => {
      try {
        if (!(await isAuthorizedAdmin(request))) {
          return NextResponse.json({ error: "Unauthorized." }, { status: 401 });
        }

        return NextResponse.json(await fetchAdminContentSources());
      } catch (error) {
        console.error(error);
        return NextResponse.json({ error: "Could not load content sources." }, { status: 500 });
      }
    },
  });
}
